### ISSUE TITLE
How to install uptrace  server in cluster mode ?

### ISSUE THREAD

**Issue by darcydai** [uptrace/uptrace#103]
I want to install an uptrace server in cluster mode, like this picture. but I didn't find docs about this. is the uptrace server stateless？
![image](https://user-images.githubusercontent.com/20854418/192412792-04b29c55-d65b-4b50-bc0e-0a64e67b25da.png)

**Comment by vmihailenco** [comment]
Like @aramperes said, you need to use Postgres backend and add some proxy in front of Uptrace: haproxy/nginx, or some cloud LB. There should not be any other gotchas.

@aramperes I also wrote a helm chart [here](https://github.com/uptrace/helm-charts). Could you take a look and check if it would be possible to join our efforts? I don't use K8s myself so feel free to change whatever looks wrong.

The Helm charts repository is [here](https://github.com/uptrace/helm-charts-repository) and is outdated, but that is fixable.

**Comment by darcydai** [comment]
> Postgres backend
Postgres backend?  instead of the clickhouse as storage？

**Comment by aramperes** [comment]
@darcydai 
> Postgres backend?  instead of the clickhouse as storage？

No, Uptrace uses Clickhouse for storing the spans still, but it also needs a separate SQL database for application storage, like alerts. #102 was just merged, so it is possible to deploy Uptrace using `Postgres+Clickhouse` instead of `sqlite+Clickhouse`.

**Comment by darcydai** [comment]
> storage

thanks
