### ISSUE TITLE
Update screenshots to use correct redirect url

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/uptrace#107]
>So I trying to setup OpenID Connect using Google, following this tutorial https://uptrace.dev/get/auth-google.html. looks like the screenshot image and the Uptrace config doesn't match. in the screenshot the Authorized redirect URIs set to http://localhost:14318/api/v1/sso/oidc/callback but the Uptrace config providing id: google, which is the Authorized redirect URIs supposed to set to http://localhost:14318/api/v1/sso/google/callback 

The same issue exists with keycloak docs - https://uptrace.dev/get/auth-keycloak.html#create-a-client-for-uptrace

If anyone has a correct screenshot, please upload it here.

- [x] update google screenshot
- [ ] update keycloak screenshot

**Comment by repodevs** [comment]
@vmihailenco  here the correct screenshot


<img width="909" alt="Screen Shot 2022-10-01 at 23 01 28" src="https://user-images.githubusercontent.com/13567128/193580785-c447c9d7-e4c4-4025-a519-fdfe39bc902e.png">

**Comment by vmihailenco** [comment]
@repodevs updated, thank you - https://uptrace.dev/get/auth-google.html

**Comment by sarathchava** [comment]
why is the redirectURI pointing to localhost? can it be made configurable?

**Comment by aramperes** [comment]
> why is the redirectURI pointing to localhost? can it be made configurable? 

@sarathchava It just has to be set to whatever hostname uptrace is accessible from your browser.

**Comment by sarathchava** [comment]
@aramperes when i tried with the url from where uptrace is accessible - i am getting 
![initialerror](https://user-images.githubusercontent.com/6793196/193964445-404fb8e5-5362-41b9-9b39-4582b87f8854.png)
![url_redirect_err](https://user-images.githubusercontent.com/6793196/193964464-752025ff-23f3-4d08-aa2f-07744bf976fb.png)
when i change redirect uri in google setting to localost - i am being redirected to proper login, but post authentication page is getting redirected to localhost.

**Comment by aramperes** [comment]
And for reference, you have to also set this in `uptrace.yml`:

```yaml
site:
  # Overrides public URL for Vue-powered UI in case you put Uptrace behind a proxy.
  addr: 'https://uptrace.mydomain.com'
```

**Comment by vmihailenco** [comment]
@sarathchava let me know if @aramperes suggestion works and I will update the docs.

**Comment by sarathchava** [comment]
@vmihailenco @anmic it does work - was able to figure it out after looking into the code. better if docs are updated. some what related is the claims param in config - for google it should be "email"

**Comment by vmihailenco** [comment]
@sarathchava alright, added a note to all 3 supported auth methods including [google](https://uptrace.dev/get/auth-google.html). The `claim: email` was already there. Let me know if anything is missing.

**Comment by vmihailenco** [comment]
Both screenshots were updated.
