### ISSUE TITLE
unexpected filter filtering spans by duration using pre-defined menu

### ISSUE THREAD

**Issue by jkrech17** [uptrace/uptrace#11]
When filtering spans by duration, receive an error

`unexpected ">" in "where span.duration ><-= 500ms"
`

Manually removing the = in the filter produces results > 

`where span.duration > 500ms`

![duration_filter](https://user-images.githubusercontent.com/3282447/157760291-e019f02c-c001-4c36-a406-7c5e09fdf24a.png)

**Comment by vmihailenco** [comment]
Thanks for the report - this should be fixed in the upcoming release.
