### ISSUE TITLE
Support FluentBit 2.0 / provide examples using OTLP

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/uptrace#126]
https://github.com/fluent/fluent-bit/releases/tag/v2.0.0

**Comment by vmihailenco** [comment]
[Ingesting logs using FluentBit](https://uptrace.dev/get/ingest/fluent-bit.html)

**Comment by lkhomenk** [comment]
Has anything changed for fluentbit configuration?
```
[OUTPUT]
    Name                 opentelemetry
    Match                *
    Host                 api.uptrace.dev
    Port                 443
    Header               uptrace-dsn https://uptrace-token@api.uptrace.dev?grpc=4317
    Compress             gzip
    Metrics_uri          /v1/metrics
    Logs_uri             /v1/logs
    Traces_uri           /v1/traces
    Log_response_payload True
    Tls                  On
    Tls.verify           Off
```
this gives an error like `[output:opentelemetry:opentelemetry.0] api.uptrace.dev:443, HTTP status=404
404 page not found`

**Comment by vmihailenco** [comment]
@lkhomenk nothing has changed, but the document was incorrect. It should be `otlp.uptrace.dev` instead of `api.uptrace.dev`.

Thanks for bringing this up.
