### ISSUE TITLE
vector return unknown variant `ndjson`

### ISSUE THREAD

**Issue by icyleaf** [uptrace/uptrace#129]
I use [this method](https://uptrace.dev/opentelemetry/structured-logging.html#vector) tranform log from vector to uptrace, in vector `http` sinks docs which the [encoding.exec](https://vector.dev/docs/reference/configuration/sinks/http/#encoding.codec) only list `json` and `text`. if fill the `ndjson` vector will return an error: 

```
unknown variant `ndjson`, expected one of `avro`, `gelf`, `json`, `logfmt`, `native`, `native_json`, `raw_message`, `text` for key `sinks.uptrace
```

**Comment by icyleaf** [comment]
solved by [this](https://github.com/uptrace/uptrace/blob/master/example/vector-logs/vector.toml#L34-L35) example.

**Comment by vmihailenco** [comment]
I will update the docs.
