### ISSUE TITLE
Zipkin JSON API does't work. 

### ISSUE THREAD

**Issue by aazf** [uptrace/uptrace#135]
## Test with curl 
```bash
curl -X POST \
  'http://uptrace:14318/api/v2/spans' \
  --header 'uptrace-dsn: http://project2_secret_token@localhost:14317/2' \
  --header 'Content-Type: application/json' \
  --data-raw '[
  {
    "id": "352bff9a74ca9ad2",
    "traceId": "5af7183fb1d4cf5f",
    "name": "get /api",
    "timestamp": 1556604172355737,
    "duration": 1431,
    "kind": "SERVER",
    "localEndpoint": {
      "serviceName": "backend",
      "ipv4": "192.168.99.1",
      "port": 3306
    },
    "remoteEndpoint": {
      "ipv4": "172.19.0.2",
      "port": 58648
    },
    "tags": {
      "http.method": "GET",
      "http.path": "/api"
    }
  }
]
'
```

## Response.
<img width="991" alt="image" src="https://user-images.githubusercontent.com/62500486/204165579-f0fda774-16ee-49ff-b06c-97b858853a14.png">

## Uptrace traces id
<img width="982" alt="image" src="https://user-images.githubusercontent.com/62500486/204165630-e0aab97c-008e-4b24-818c-c1865bdefdc3.png">

**Comment by vmihailenco** [comment]
The trace is created with id "00000000000000005af7183fb1d4cf5f". You can use search to find it by id.

The UI is empty because the trace is created at `2019-04-30 09:02:52.355737` and the UI only shows the data for the last hour.

How do you plan to use Zipkin API?
