### ISSUE TITLE
How to override kind, status value from vector?

### ISSUE THREAD

**Issue by aazf** [uptrace/uptrace#136]
https://github.com/uptrace/uptrace/blob/b402522a5188d7d14c0d697102e78708285fdda5/pkg/tracing/vector_handler.go#L90-L92

```
curl -X POST \
  'http://uptrace:14318/api/v1/vector/logs' \
  --header 'uptrace-dsn: http://project2_secret_token@localhost:14318/2' \
  --header 'Content-Type: application/x-ndjson' \
  --data-raw '{
  "kind": "CLIENT",
  "log.message": "asdfasdfe-xx-28",
  "path": "/aaasdfew",
  "service.name": "aaa",
  "service.version": "1.1",
  "source_type": "http"
}'
```

This Kind can't override. Is any other way to override them?

**Comment by vmihailenco** [comment]
Those are span fields and their meaning is not defined for logs. I guess we should allow to set them, but it is not clear what the use case is.

>Is any other way to override them?

No, not at the moment.

**Comment by vmihailenco** [comment]
This should be supported in v1.3.0. See changelog for details.
