### ISSUE TITLE
Source available, not open source

### ISSUE THREAD

**Issue by jkowall** [uptrace/uptrace#138]
You claim this project is "open source" while you are using a non OSI approved license. This project is not open source. 

If you want to understand why this is a problem and misleading have a read of this article: https://www.theregister.com/2022/09/05/open_source_databases/

**Comment by vmihailenco** [comment]
Hey @jkowall,

You are right about this and I have explained why we do this in the end of the [README](https://github.com/uptrace/uptrace/blob/master/README.md). My main point is that our competitors do the same (or even worse) and I don't see that changing any time soon. You can easily find them by checking "open-source APM" in Google.

Usually, I also ask what are the real downsides of using source-available Uptrace vs truly open-source software like Jaeger. It does not go well. And the article you linked does not resonate with me, i.e. I don't find it relevant in the domain I am working.

That said, I will happily use the OSI approved terms as soon as our competitors do the same. Being the only nice guy in the room will only make my life harder and nothing else.

**Comment by jkowall** [comment]
Well, the main reason why it's important is that as a vendor using a vendor-preferable license, it puts the users at risk when you make a business decision to change the license. It means that users are locked into your reasoning. This has happened time and time again, and causes many problems for users who want to use the technology for their preferences. 

I entirely agree that you can market it however you want on your website, but when it comes to GitHub you are speaking to developers and deeper users who care about what they contribute to and get involved in. This is the reason we have the Apache Software Foundation, The Linux Foundation, and the CNCF. If someone just decided to just change the license on Linux, Kubernetes, Flink, Spark, or Kafka there would be numerous issues for the world.

**Comment by vmihailenco** [comment]
>This has happened time and time again, and causes many problems for users who want to use the technology for their preferences.

Yes, it happened numerous time and will happen again, because Apache 2.0 does not forbid you to change the license for the new code. It is exactly the same with BSL and probably with any other license.

>but when it comes to GitHub you are speaking to developers and deeper users who care about what they contribute to and get involved in

We don't require you to sign anything when you are contributing to Uptrace.

>This is the reason we have the Apache Software Foundation, The Linux Foundation, and the CNCF.

Yes, a foundation that can fund the work makes real difference. Or an active community of developers. But I don't think this is a viable route for a project like Uptrace.

**Comment by vmihailenco** [comment]
Hopefully I've explained what we do and why. Closing for now.
