### ISSUE TITLE
In example, docker-compose up failed

### ISSUE THREAD

**Issue by puniey** [uptrace/uptrace#14]
docker-uptrace-1  |       *ch.Error: DB::Exception: Missing columns: 'time' while processing query: 'project_id, `span.system`, `span.group_id`, time', required columns: 'project_id' 'span.system' 'time' 'span.group_id' 'project_id' 'span.system' 'time' 'span.group_id'
docker-uptrace-1  | [ch]  09:03:18.366   ALTER                 5.539ms  ALTER TABLE ch_migration_locks DROP COLUMN col1
docker-uptrace-1  | 2022/03/23 09:03:18 DB::Exception: Missing columns: 'time' while processing query: 'project_id, `span.system`, `span.group_id`, time', required columns: 'project_id' 'span.system' 'time' 'span.group_id' 'project_id' 'span.system' 'time' 'span.group_id'

**Comment by vmihailenco** [comment]
@puniey thanks for the report. This should be fixed in v0.2.10. You can pull new images and try again:

```shell
docker-compose pull
```
