### ISSUE TITLE
OTLP HTTP ingestion does not work

### ISSUE THREAD

**Issue by amikoliunas** [uptrace/uptrace#149]
Hello, 

I am trying to run Uptrace locally, in minikube.
I installed uptrace using steps provided here: https://github.com/uptrace/helm-charts
Then configured my OpenTelemetry collector to send metrics, logs and traces to Uptrace:

![image](https://user-images.githubusercontent.com/196408/214013178-b04d0cec-b0ab-4126-bd3f-b4dd32ab9ee2.png)

However when I look into OpenTelemetry collector logs, I see that exporting to uptrace does not work. 
By the way, I can open Uptrace UI using http://localhost:14318
![image](https://user-images.githubusercontent.com/196408/214013544-204e0275-9ec0-4b73-a996-2e3bfa3515ec.png)

Any ideas what could be wrong with API? Why it returns this error?
Permanent error: error exporting items, request to http://localhost:14318/v1/metrics responded with HTTP Status Code 405

**Comment by vmihailenco** [comment]
Hi,

This will be fixed in v1.3.1. We just did not suport OTLP/HTTP API for metrics, only OTLP/GRPC.
