### ISSUE TITLE
Example docker configuration doesn't persist the uptrace.sqlite3 database file

### ISSUE THREAD

**Issue by gabriel-v** [uptrace/uptrace#152]
In [the docker deployment example](https://github.com/uptrace/uptrace/blob/4a6dff059613de83570180c917c86862ce14bbb2/example/docker/docker-compose.yaml#L25), the `/var/lib/uptrace` directory is mounted as a volume.

But in its respective [documentation example for uptrace.yml](https://github.com/uptrace/uptrace/blob/4a6dff059613de83570180c917c86862ce14bbb2/example/docker/uptrace.yml#L291), the database storage path is given as `file:uptrace.sqlite3` which, with default docker image arguments, ends up being `/uptrace.sqlite3` in the `/` folder, instead of `/var/lib/uptrace/uptrace.sqlite3`.

This results in 30s of confusion so I spent another 90s to write this description and open a PR here

**Comment by vmihailenco** [comment]
Thanks for your time!
