### ISSUE TITLE
Hosting UI with path prefix

### ISSUE THREAD

**Issue by gabriel-v** [uptrace/uptrace#158]
Path prefix customization allows hosting this alongside the many other dashboards any org uses under a single reverse proxy.

For example, Grafana has [serve_from_sub_path = true](https://grafana.com/tutorials/run-grafana-behind-a-proxy/).

Not having this feature means we either need a new subdomain for Uptrace, or host it on some non-standard port.

There is a [config flag](https://github.com/uptrace/uptrace/blob/4dda1a522fdbe000be978accec6e48be0668a27d/config/uptrace.yml#L248-L250) to set the Domain TLD, but adding a path prefix to it does not work. Uptrace accepts it, but the UI still expects to be served from the path `/`.

I guess the patch would work like this:
-  [the config go code](https://github.com/uptrace/uptrace/blob/636439e38c73228b9959ee4dc01ec11d33719a7e/pkg/bunconf/config.go#L86) should extract path prefix
- [the vue router](https://github.com/uptrace/uptrace/blob/636439e38c73228b9959ee4dc01ec11d33719a7e/vue/src/router/index.ts) should prepend the prefix to all the links in there

I'm not familiar with go or vue, so here are some questions:
- how should we send the prefix to the UI build process?
- how do you want the config to look like? A separate `site.prefix` key or directly in the `site.addr` key?  
- is there any go HTTP server router that also needs the prefix?

**Comment by vmihailenco** [comment]
>how should we send the prefix to the UI build process?

The UI is pre-built and embedded into the Go binary once Uptrace app is compiled. So it would not work.

I believe https://github.com/uptrace/uptrace/pull/159 should do the trick.
