### ISSUE TITLE
Configuration for Elixir projects

### ISSUE THREAD

**Issue by mindreframer** [uptrace/uptrace#162]
Hey, this looks like a really great project and I would like to use it with Elixir! 

But I have troubles to get my traces sent to Uptrace, even though the URL and rest looks OK. I have created a small GIT repo to reproduce this issue: 

- https://github.com/mindreframer/otel_getting_started

Maybe somebody can give me a hint, what is still missing there.

**Comment by vmihailenco** [comment]
Hey,

Looking at the Uptrace logs

```
[bunrouter]  23:30:53.719  1741fa092f9068d0f1f2f197f127846f   405         31µs   POST     /1/v1/traces
[bunrouter]  23:45:07.757  1741fad0083fa71027fe37c5ac8994e5   405          6µs   POST     /1
[bunrouter]  23:48:45.096  1741fb02a2abd6207bea865c6e3e4e7f   405          8µs   POST     /1/v1/traces
```

`POST     /1/v1/traces` is incorrect and should be just `POST     /v1/traces` without the project id.

I believe the correct Elixir config is:

```
config :opentelemetry_exporter,
  otlp_protocol: :grpc,
  otlp_compression: :gzip,
  otlp_endpoint: "http://localhost:14317",
  otlp_headers: [{"uptrace-dsn", "http://project1_secret_token@localhost:14318/1"}]
```

@mindreframer could you try that?

**Comment by mindreframer** [comment]
@vmihailenco Hey thanks! I can confirm, this configuration seems to work: 

```elixir
config :opentelemetry_exporter,
  otlp_protocol: :http_protobuf,
  otlp_compression: :gzip,
  otlp_endpoint: "http://localhost:14318",
  otlp_headers: [{"uptrace-dsn", "http://project1_secret_token@localhost:14318/1"}]
```


also following works too, for GRPC: 

```elixir
config :opentelemetry_exporter,
  otlp_protocol: :grpc,
  otlp_compression: :gzip,
  otlp_endpoint: "http://localhost:14317",
  otlp_headers: [{"uptrace-dsn", "http://project1_secret_token@localhost:14317/1"}]
```

It would be great if we  document this in the docs, I've spent too much time trying to figure it out. 


Thanks! Another question: it is possible to exclude the "serve" related metrics / spans from the projects data? It makes digging through data more confusing... 
<img width="884" alt="Screenshot 2023-02-11 at 17 37 55" src="https://user-images.githubusercontent.com/1232/218269909-3bfe4d9f-ce57-4fa9-aff6-b5741a33f602.png">

**Comment by vmihailenco** [comment]
>it is possible to exclude the "serve" related metrics / spans from the projects data?

Just use a separate project for your application, e.g. change DSN from `http://project1_secret_token@localhost:14317/1` to `http://project2_secret_token@localhost:14317/2` and open the 2nd project in the UI.

>It would be great if we document this in the docs

Will do :+1:

**Comment by vmihailenco** [comment]
@mindreframer here is the documentation - https://uptrace.dev/get/opentelemetry-erlang-elixir.html . Let me know if you spot mistakes or missing details.

**Comment by mindreframer** [comment]
@vmihailenco Wow! That's is some nice looking documentation. ❤️  Awesome, thanks for doing it! I'll report any issues, if I encounter any. 

Have a nice Sunday!

**Comment by vmihailenco** [comment]
Thank you! Have a nice day as well.

I am closing this for now.
