### ISSUE TITLE
Unexpected histogram from PeriodicReader

### ISSUE THREAD

**Issue by yuhongyu879** [uptrace/uptrace#170]
When exporting histogram metrics to uptrace, the value in ch is different from recording. the recoding code shows below:

meterProvider := metric.NewMeterProvider(
		metric.WithReader(metric.NewPeriodicReader(exporter, metric.WithInterval(time.Duration(5)*time.Second)))
)
// ...
m.LatencyHistogram.Record(ctx, float64(latencyMs))

data in measure_minutes_buffer (unit: microseconds, value will be 175 after set unit to millsecond)
┌────────────────time─┬─sum(sum)─┬─sum(count)─┬─arrayElement(quantilesBFloat16Merge(0.5)(histogram), 1)─┬─arrayElement(quantilesBFloat16Merge(0.9)(histogram), 1)─┐
│ 2023-02-23 08:34:00 │  6689280 │          7 │                                                    9984 │                                                    9984 │
│ 2023-02-23 08:33:00 │ 32853401 │         29 │                                                    9984 │                                                    9984 │
│ 2023-02-23 08:32:00 │ 30201226 │         30 │                                                    9984 │                                                    9984 │
│ 2023-02-23 08:31:00 │ 32923201 │         31 │                                                    9984 │                                                    9984 │
│ 2023-02-23 08:30:00 │ 29531220 │         31 │                                                    9984 │                                                    9984 │
│ 2023-02-23 08:29:00 │ 27540681 │         30 │                                                    9984 │                                                    9984 │
│ 2023-02-23 08:28:00 │ 28818009 │         27 │                                                    9984 │                                                    9984 │
│ 2023-02-23 08:27:00 │ 29554054 │         28 │                                                    9984 │                                                    9984 │
│ 2023-02-23 08:26:00 │ 28989268 │         27 │                                                    9984 │                                                    9984 │
│ 2023-02-23 08:25:00 │ 31246608 │         29 │                                                    9984 │                                                    9984 │
└─────────────────────┴──────────┴────────────┴─────────────────────────────────────────────────────────┴─────────────────────────────────────────────────────────┘

**Comment by vmihailenco** [comment]
Please provide more details. It is not clear what is wrong/expected here.

**Comment by yuhongyu879** [comment]
I want to record request time in a Gin middleware, but the `pxx($latency)` is incorrect. So I queried ClickHouse:


SELECT
    time,
    sum(sum),
    sum(count),
    quantilesBFloat16Merge(0.5)(histogram)[1],
    quantilesBFloat16Merge(0.9)(histogram)[1]
FROM measure_minutes_buffer
WHERE (project_id = 2) AND (metric LIKE '%ginerror%')
GROUP BY time
ORDER BY time DESC
LIMIT 10

![image](https://user-images.githubusercontent.com/31095891/220868285-1e3a6f1b-bfc7-4948-b911-07f8cb8fceb1.png)

The results shown above are all 9984, while it's definitely not the real latency. But I can't figure out what's wrong with my code.

Actually, I turned off `metrics_from_spans` because spans are sampled in a ratio. So, I want to record metrics (request count/error rate/request time) manully. Can you show some tips on how to correctly record histogram metrics to Uptrace? (The [doc](https://uptrace.dev/opentelemetry/go-metrics.html#histogram) is outdated.) The complete code is shown below:

```
type MetricMiddleware struct {
	service  string
	endpoint string
	dsn      string
	env      string

	RequestCount     instrument.Int64Counter
	ErrorCount       instrument.Int64Counter
	LatencyHistogram instrument.Float64Histogram
}

func (m *MetricMiddleware) initMetric() (*metric.MeterProvider, error) {
	opts := []otlpmetricgrpc.Option{
		otlpmetricgrpc.WithEndpoint(m.endpoint),
		otlpmetricgrpc.WithInsecure(),
		otlpmetricgrpc.WithHeaders(map[string]string{
			"uptrace-dsn": m.dsn,
		}),
	}
	exporter, err := otlpmetricgrpc.New(context.Background(), opts...)
	if err != nil {
		return nil, err
	}
	meterProvider := metric.NewMeterProvider(
		metric.WithReader(metric.NewPeriodicReader(exporter, metric.WithInterval(time.Duration(5)*time.Second))),
		metric.WithResource(defaultAttributes(m.service, m.env)),
	)
	global.SetMeterProvider(meterProvider)
	return meterProvider, nil
}

func (m *MetricMiddleware) Middleware() gin.HandlerFunc {

	return func(c *gin.Context) {
		ctx := c.Request.Context()
		startTime := time.Now()

		defer func() {
			latencyMs := time.Since(startTime).Microseconds()

			m.RequestCount.Add(ctx, 1)

			if c.Writer.Status() >= 400 {
				m.ErrorCount.Add(ctx, 1)
			}

			m.LatencyHistogram.Record(ctx, float64(latencyMs))
		}()

		c.Next()
	}
}

```

**Comment by yuhongyu879** [comment]
BTW, how does uptrace convert span to metrics?

**Comment by vmihailenco** [comment]
@yuhongyu879 most likely the problem is with `Float64Histogram` which uses the [fixed number of buckets](https://github.com/open-telemetry/opentelemetry-go/blob/cc8bdaaad4b4a788f68ac59da4610d597d75f67b/sdk/metric/reader.go#L150-L153) and is not very accurate. That's why all values are close to 10000.

[Exponential histograms](https://github.com/open-telemetry/opentelemetry-go/issues/2966) are much better, but are not supported by Go yet.

**Comment by yuhongyu879** [comment]
Thanks. But metrics in example project are all works fine: process.runtime.go.gc.pause_ns, go.sql.query_timing
![image](https://user-images.githubusercontent.com/31095891/220931215-67e7952e-3179-4b8a-b312-77fe990a8b54.png)

**Comment by vmihailenco** [comment]
Try to replace `.Microseconds()` with `.Milliseconds()` so the result better fits into the provided buckets.

**Comment by yuhongyu879** [comment]
Value is closed to 175 after change to millseconds. it seems to need more work to do
