### ISSUE TITLE
Column name without alias

### ISSUE THREAD

**Issue by leonyu879** [uptrace/uptrace#171]
When a column has a filter but no alias, there is a new column with one extra comma.
![image](https://user-images.githubusercontent.com/31095891/221107783-8f4624be-55a3-4b10-8a1e-9d571d9b86c3.png)

should we use MetricName here?
https://github.com/uptrace/uptrace/blob/13d7c93c11a0ad463290120582effe2981b967d5/pkg/metrics/upql/compile.go#L37-L44
https://github.com/uptrace/uptrace/blob/13d7c93c11a0ad463290120582effe2981b967d5/pkg/metrics/upql/engine.go#L59-L62

**Comment by vmihailenco** [comment]
Thanks for reporting. I will look into this after porting changes we already have in https://github.com/uptrace/cloud-changelog/issues/11

**Comment by vmihailenco** [comment]
This should be fixed in the master branch.
