### ISSUE TITLE
facing a import error with python version 3.6.9

### ISSUE THREAD

**Issue by rupeshkumar1995** [uptrace/uptrace#174]
ImportError: cannot import name '_metrics' 
 hi i am facing this issue with django project with python env version 3.6.9

**Comment by vmihailenco** [comment]
OpenTelemetry requires Python >=3.7. So you need to upgrade your Python and then make sure you are on the latest uptrace-python version which is currently **1.16.0**.

If you have more questions, please ask at https://github.com/uptrace/uptrace-python
