### ISSUE TITLE
Can't find meta migration sql file

### ISSUE THREAD

**Issue by yuhongyu879** [uptrace/uptrace#184]
Hi @vmihailenco, i have a problem in cluster mode, there's no table `metrics` found, where can i find the meta sql files?

Problems:
`initSpanMetrics failed	{"error": "createSpanMetric \"uptrace.tracing.spans\" failed: createSpanMetricMeta failed: ERROR: relation \"metrics\" does not exist (SQLSTATE=42P01)"}`

**Comment by yuhongyu879** [comment]
https://github.com/uptrace/uptrace/commit/244f13f0261bacfaa883641dce25b22ae86b601b#diff-30735cb25f5d933d87867774d1dc1957e53a57759d91574d4a5de3ee754a328b

may be should add this to the bun init up sql?

**Comment by vmihailenco** [comment]
@yuhongyu879 if you are using the master branch, then it is currently broken. We are in the middle of the big migration..

**Comment by yuhongyu879** [comment]
ok, I can't use pg in other versions, right?

**Comment by vmihailenco** [comment]
@yuhongyu879 you can, see this [example](https://github.com/uptrace/bun/tree/master/example/opentelemetry) which is configured to work with PostgreSQL.

**Comment by yuhongyu879** [comment]
Got it thx

**Comment by yuhongyu879** [comment]
Got it thx
