### ISSUE TITLE
Attrs missing in metric

### ISSUE THREAD

**Issue by leonyu879** [uptrace/uptrace#186]
https://github.com/uptrace/uptrace/blob/ae6bb75f6a1a785295b8ef522b7550ce1ea6ef7d/pkg/metrics/measure_processor.go#L191

When setting attributes to counter, uptrace can't find prev metric of current attribute, that make delta sum to wrong value . should `initMeasure` be called before `processMeasure`?

**Comment by yuhongyu879** [comment]
Does prev metric lost in cluster mode?https://github.com/uptrace/uptrace/blob/ae6bb75f6a1a785295b8ef522b7550ce1ea6ef7d/pkg/metrics/cumtodelta.go#L74~L87

**Comment by vmihailenco** [comment]
>should initMeasure be called before processMeasure?

Right, I will send a fix.

>Does prev metric lost in cluster mode?

@yuhongyu879 yes, I guess we should document this restriction. It is the same as with https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor#scaling-collectors-with-the-tail-sampling-processor

>> This processor requires all spans for a given trace to be sent to the same collector instance for the correct sampling decision to be derived. When scaling the collector, you'll then need to ensure that all spans for the same trace are reaching the same collector. You can achieve this by having two layers of collectors in your infrastructure: one with the [load balancing exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/loadbalancingexporter), and one with the tail sampling processor.

**Comment by yuhongyu879** [comment]
>> should initMeasure be called before processMeasure?

>Right, I will send a fix.

Released in v1.4.0? does the new version compatible with v1.3.1(clickhouse/pg)?

> @yuhongyu879 yes, I guess we should document this restriction. It is the same as with https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor#scaling-collectors-with-the-tail-sampling-processor

What a bad news, metric hasn't been supported yet. i'm wondering does the cloud version deployed in a super powerful node for each tenant.

**Comment by vmihailenco** [comment]
>Released in v1.4.0? does the new version compatible with v1.3.1(clickhouse/pg)?

No, writing a migration would require too much work and it would be hard to handle all cases.

We could release a v.1.3.2 with the fix, but I wouldn't recommend it since there are many other small fixes in v1.4.0.

**Comment by yuhongyu879** [comment]
> We could release a v.1.3.2 with the fix, but I wouldn't recommend it since there are many other small fixes in v1.4.0.

v1.4.0 is acceptable. i have made a release of our private using.

> No, writing a migration would require too much work and it would be hard to handle all cases.

This means i can't upgrade my deployment to the new version? we are using v1.3.1.

> i'm wondering does the cloud version deployed in a super powerful node for each tenant.

I should refrain from inquiring about the specifics of the cloud version. Could you please provide some advice for our situation? Although we prefer the cloud version, we are limited to certain cloud providers, and the network must be within the same VPC.
