### ISSUE TITLE
UpsertMetric bugs maybe

### ISSUE THREAD

**Issue by leonyu879** [uptrace/uptrace#189]
1. https://github.com/uptrace/uptrace/blob/master/pkg/metrics/metric.go#L103~#L112 missing attr keys.
2. https://github.com/uptrace/uptrace/blob/master/pkg/metrics/measure_processor.go#L351~#L353 metric touch doesn't been updated.

**Comment by vmihailenco** [comment]
Thanks for the report! I've tried to fix this in https://github.com/uptrace/uptrace/commit/c7006985e8014886e68513929ea41c4b79867c7e
