### ISSUE TITLE
Alert should not be deduplicated.

### ISSUE THREAD

**Issue by leonyu879** [uptrace/uptrace#192]
https://github.com/uptrace/uptrace/blob/master/pkg/alerting/span_error.go#L48

https://github.com/uptrace/uptrace/blob/master/pkg/bunapp/pgmigrations/20220926100949_init.up.sql#L255

field `state` is not effected, alert will be deduplicated even when it has been closed. also may be we should put state into the unique index? #

**Comment by vmihailenco** [comment]
@leonyu879 we don't create new alerts when state is changed. Instead, we send a notification for the existing alert and create an entry in `alert_events` table.

>alert will be deduplicated even when it has been closed

Could you try it? It should be working.

**Comment by leonyu879** [comment]
> Instead, we send a notification for the existing alert

now im using email channel for error alerting, only the first notification been send, when the error occurred after the intervals(group/repeat/3hour...), no more notification received. based on the code(https://github.com/uptrace/uptrace/blob/master/pkg/alerting/span_error.go#L48-#L66/https://github.com/uptrace/uptrace/blob/master/pkg/alerting/alert.go#L282-#L289), notification will not be send cause there's already a closed(or open) alert. `createAlert` will not be call right?

if new alerts will not be created, should the old one be reopened again? i think it's the normal way we handle alerts.

**Comment by vmihailenco** [comment]
>if new alerts will not be created, should the old one be reopened again? i think it's the normal way we handle alerts.

Yes, this is how it works in the Cloud version. That logic was not ported yet, but I will try to do it today. Thanks for reminding.

**Comment by leonyu879** [comment]
Thanks a lot. 

not only the closed alert should be reopen, but also the opened alert should be notified after a period when the error occurred continuously. based the code and my test, it doesn't - -.

**Comment by vmihailenco** [comment]
>based the code and my test, it doesn't - -. does it works for you?

Not in the community version, but it does work in the Enterprise/Cloud version.

I will ping you once it is fixed. Thanks for testing!

**Comment by vmihailenco** [comment]
Should be fixed by https://github.com/uptrace/uptrace/commit/fdded5e0b9823c47a6e070ff67c9fe13df0407bc

@leonyu879 could you try it please?

**Comment by leonyu879** [comment]
Nice work.
