### ISSUE TITLE
Support for Dark Mode

### ISSUE THREAD

**Issue by gaby** [uptrace/uptrace#195]
I searched and didn't find any issues asking for dark mode so I figured to create one. Currently all of uptrace including the website lack dark mode support. Are there plans to add dark-mode to it?

**Comment by invaderb** [comment]
In the mean time you could use dark reader chrome extension or something similar, I test out and looks pretty good using it.

**Comment by gaby** [comment]
@invaderb Sadly I can't force users to install extensions

**Comment by gzuidhof** [comment]
Hey @vmihailenco, maybe as a 20/80 solution a button that does the following can do (try it in your console).
```javascript
document.body.style.filter = document.body.style.filter ? "" : "invert(1) hue-rotate(180deg)"
```

It's problematic when there are images (usually you wouldn't want to darken those), but for the dashboard it doesn't look that bad:

![Screenshot 2024-03-13 at 00 13 10](https://github.com/uptrace/uptrace/assets/1039510/8ee0421e-5009-417f-a9f8-25d546a3afd7)

**Comment by vmihailenco** [comment]
Vuetify, the UI framework we're using, already supports dark mode and it will probably work better than the neat hack you've provided. Custom components will requires additional work though...

So far we've just assumed that the dark mode is not such a big deal, but maybe it is...

**Comment by gaby** [comment]
@vmihailenco It was enough reason for me to go with something else. Recently I noticed there's 0 unit-tests running in the CI and that push me even further away 😂

**Comment by vmihailenco** [comment]
@gaby I can only promise to add a dark mode. Tests are elsewhere and maintaining them in 2 places is not fun.

**Comment by gaby** [comment]
@vmihailenco Thank you! Where are the tests hosted?

**Comment by vmihailenco** [comment]
@gaby tests are not on GitHub.

The dark mode is available in the cloud now: https://app.uptrace.dev/play

![dark-mode](https://github.com/uptrace/uptrace/assets/290976/4e6e6ac1-7b8d-4bb6-bf0e-fa567cf0316f)

BTW [Dark Reader ](https://chromewebstore.google.com/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?pli=1)is not too bad too:

**Comment by gaby** [comment]
@vmihailenco Awesome looks great! Lookifng forward for this being in the self hosted 💪

**Comment by gaby** [comment]
Fixed via https://github.com/uptrace/uptrace/releases/tag/v1.7.0

@vmihailenco Thank you! 💪
