### ISSUE TITLE
Clickhouse request errors

### ISSUE THREAD

**Issue by like-a-freedom** [uptrace/uptrace#2]
Good day!

I've started uptrace setup via Docker and got an errors in UI:

<img width="1440" alt="Screenshot 2021-12-29 at 12 45 35" src="https://user-images.githubusercontent.com/4669970/147649056-bade0ed1-0005-4735-a607-e599692d10bd.png">

`*ch.Error: DB::Exception: Unknown function toFloat64OrDefault. Maybe you meant: ['toFloat64OrNull','dictGetFloat64OrDefault']: While processing toFloat64OrDefault(`span.duration`)`

Uptrace logs:

```
[bunrouter]  09:45:30.094   500     16.918ms   GET      /api/tracing/groups?time_gte=2021-12-29T08:46:00.000Z&time_lt=2021-12-29T09:46:00.000Z&query=group+by+span.group_id+%7C+span.count_per_min+%7C+span.error_pct+%7C+p50(span.duration)+%7C+p90(span.duration)+%7C+p99(span.duration)&system=http:unknown_service          *ch.Error: DB::Exception: Unknown function toFloat64OrDefault. Maybe you meant: ['toFloat64OrNull','dictGetFloat64OrDefault']: While processing toFloat64OrDefault(`span.duration`)

[ch]  09:45:30.696   SELECT               68.642ms  SELECT count() / 60 AS "span.count_per_min", countIf(`span.status_code` = 'error') / count() AS "span.error_pct", quantileTDigest(0.5)(toFloat64OrDefault(s."span.duration")) AS "p50(span.duration)", quantileTDigest(0.9)(toFloat64OrDefault(s."span.duration")) AS "p90(span.duration)", quantileTDigest(0.99)(toFloat64OrDefault(s."span.duration")) AS "p99(span.duration)", s."span.group_id" AS "span.group_id", any(s."span.system") AS "span.system", any(s."span.name") AS "span.name" FROM "spans_index_buffer" AS "s" WHERE (s.`span.time` >= '2021-12-29 08:46:00') AND (s.`span.time` < '2021-12-29 09:46:00') AND (s.`span.system` = 'http:unknown_service') GROUP BY "span.group_id" LIMIT 1000       *ch.Error: DB::Exception: Unknown function toFloat64OrDefault. Maybe you meant: ['toFloat64OrNull','dictGetFloat64OrDefault']: While processing toFloat64OrDefault(`span.duration`) 

[bunrouter]  09:45:30.607   500    108.234ms   GET      /api/tracing/groups?time_gte=2021-12-29T08:46:00.000Z&time_lt=2021-12-29T09:46:00.000Z&query=group+by+span.group_id+%7C+span.count_per_min+%7C+span.error_pct+%7C+p50(span.duration)+%7C+p90(span.duration)+%7C+p99(span.duration)&system=http:unknown_service          *ch.Error: DB::Exception: Unknown function toFloat64OrDefault. Maybe you meant: ['toFloat64OrNull','dictGetFloat64OrDefault']: While processing toFloat64OrDefault(`span.duration`)
```

Clickhouse version: `altinity/clickhouse-server:21.8.12.1.testingarm` (cause I have macbook on m1 chip)

**Comment by vmihailenco** [comment]
If you can, upgrade to ClickHouse 21.11 or 21.12. We are using those versions and they are pretty stable.

I will see if we can remove `toFloat64OrDefault` usage to make it work on older CH versions.

**Comment by like-a-freedom** [comment]
Thank you!
It works well on `yandex/clickhouse-server:21.12.3.32`, so I'll close this issue because it's just a development environment.

**Comment by faceair** [comment]
> If you can, upgrade to ClickHouse 21.11 or 21.12. We are using those versions and they are stable & usable in production.
> 
> I will see if we can remove `toFloat64OrDefault` usage to make it work on older CH versions.

@vmihailenco Are there any plans to support lower versions of clickhouse now?

**Comment by vmihailenco** [comment]
ClickHouse is developed rapidly so the requirement to support old versions can be especially frustrating. So I think no, we will only support 3 last ClickHouse versions which is v21.11 at the moment.
