### ISSUE TITLE
Support for servicegraph

### ISSUE THREAD

**Issue by leonyu879** [uptrace/uptrace#204]
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/servicegraphprocessor

we can find the root cause based on the service graph.

**Comment by vmihailenco** [comment]
Thanks for bringing this. Looks like can use this to implement https://github.com/uptrace/cloud-changelog/issues/8

**Comment by vmihailenco** [comment]
I can't make Otelcol's [servicegraph](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/servicegraphconnector) to generate any metrics.

```
connectors:
  servicegraph:
    latency_histogram_buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]
    store:
      ttl: 5m
      max_items: 1000000

exporters:
  otlp/uptrace:
    endpoint: host.docker.internal:14317
    tls:
      insecure: true
    headers: { 'uptrace-dsn': 'http://project1_secret_token@localhost:14317/1' }
  debug:

service:
  pipelines:
    metrics/servicegraph:
      receivers: [servicegraph]
      processors: []
      exporters: [otlp/uptrace, debug]
```

It looks like data is coming through, but Otelcol can't find any matching edges and does not generate any metrics.

![servicegraph](https://github.com/uptrace/uptrace/assets/290976/06060c66-5f2a-4ff7-8ef7-6c818661f72a)

**Comment by vmihailenco** [comment]
Done in master.
