### ISSUE TITLE
Image for Arm64

### ISSUE THREAD

**Issue by robertonav20** [uptrace/uptrace#207]
Hi,
i want try the uptrace stack on my raspberry k3s cluster but any image is available for arm64 https://hub.docker.com/r/uptrace/uptrace/tags

Can you push a multi architecture image pls?

**Comment by robertonav20** [comment]
Thank you

**Comment by vmihailenco** [comment]
@robertonav20 you're welcome and sorry for the delay.

**Comment by robertonav20** [comment]
Hi,
i comment again on this closed task to link this [issue](https://github.com/ClickHouse/ClickHouse/issues/50852) open on clickhouse server because it isn't work on rpi4, so i can't deploy uptrace stack.

**Comment by vmihailenco** [comment]
You could try https://hub.docker.com/r/bitnami/clickhouse/tags to see if their linux/arm64 is any better. That's probably all we can do...
