### ISSUE TITLE
Aggregate using custom span attributes breaks.

### ISSUE THREAD

**Issue by CarlosDescalziIM** [uptrace/uptrace#224]
I'm sending a custom attribute "SampleRate" with the span, when I try to do sum(SampleRate) on tracing tab, shows nothing on the page and this error appears in log:
```
*ch.Error: DB::Exception: Illegal type String of argument for aggregate function sum
```

For the moment I worked it around here: https://github.com/uptrace/uptrace/blob/master/pkg/tracing/span_filter.go#L293
With this:
```go
	default:
		if name.FuncName != "" {
			b = append(b, name.FuncName...)
			b = append(b, "(toFloat64OrZero("...)
		}

		b = AppendCHAttrExpr(b, name.AttrKey)

		if name.FuncName != "" {
			b = append(b, "))"...)
		}

		return b
	}
```

**Comment by CarlosDescalziIM** [comment]
btw, should be nice to have a function "sum per minute" available for custom attributes.

**Comment by vmihailenco** [comment]
Thanks for reporting. It will be fixed in the next release.

>should be nice to have a function "sum per minute" available for custom attributes.

Not sure I follow. How it will different from just `sum`?

**Comment by vmihailenco** [comment]
Makes sense, but it will take some time. I've created https://github.com/uptrace/uptrace/issues/225 to track it.

This issue should be fixed in the master branch.
