### ISSUE TITLE
Docker demo on aarch64

### ISSUE THREAD

**Issue by efumagal** [uptrace/uptrace#227]
Hi, 
I tried to run the docker compose example but mailhog/mailhog:v1.0.1 and uptrace/uptrace:1.4.8 are not starting giving in the logs:
uptrace_1     | exec /entrypoint.sh: exec format error
and
exec /usr/local/bin/MailHog: exec format error

Is aarch64 supported ?

Thanks

**Comment by vmihailenco** [comment]
Only linux/amd64 is supported now. I am trying to add support for linux/arm64 in https://github.com/uptrace/uptrace/pull/230
