### ISSUE TITLE
Add Tempo-like datasource for Grafana

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/uptrace#229]
5 upvotes and this feature will be added :+1:

**Comment by vmihailenco** [comment]
Done in https://github.com/uptrace/uptrace/commit/26a208bf252b78a3f9d5bd6484aa316b472bc818. Should be available in the next release: 1.5.0-beta.2 and above.

TraceQL is NOT supported, but Search tab should be fully supported.

**Comment by jasonhu** [comment]
commit https://github.com/uptrace/uptrace/commit/26a208bf252b78a3f9d5bd6484aa316b472bc818 have not merge to master branch now.
