### ISSUE TITLE
the detail guide

### ISSUE THREAD

**Issue by bruse-peng** [uptrace/uptrace#23]
can you provide the detail guide README from configration to use with diffrent language

**Comment by vmihailenco** [comment]
@bruse-peng did you see https://get.uptrace.dev/guide/ ? Let me know what information is missing and I will try to improve that.

**Comment by bruse-peng** [comment]
> @bruse-peng did you see https://get.uptrace.dev/guide/ ? Let me know what information is missing and I will try to improve that.

1、you can provide the Architecture diagram, how the data flow works, such as the elastic APM , 
![elacticapm](https://user-images.githubusercontent.com/47881861/160377591-a401fed6-9ab8-4cf2-a0e4-81b99f1a4514.png)

2、many of us not the developer  you should privide the detail install document

3、you can also privide the the advantage compared with elastic apm or zpkin or skywalking

**Comment by vmihailenco** [comment]
>many of us not the developer you should privide the detail install document

Could you try https://get.uptrace.dev/guide/#installation? It is a few shell commands so I am not sure how to further simplify it.

>you can provide the Architecture diagram, how the data flow works, such as the elastic APM ,
>you can also privide the the advantage compared with elastic apm or zpkin or skywalking

Sure, I will write some introduction and will post it here.

**Comment by bruse-peng** [comment]
when i run uptrace --config=uptrace.yml ch reset it arise error how to resolve it

[root@fluent-bit-clinet-server uptrace]# uptrace --config=uptrace.yml ch reset
[ch]  02:31:57.968   CREATE TABLE          5.851ms  CREATE TABLE IF NOT EXISTS ch_migrations (name String, group_id Int64, migrated_at DateTime, sign Int8) Engine = CollapsingMergeTree(sign) ORDER BY (name)        *errors.errorString: ch: ClickHouse server uses timezone="Asia/Shanghai", expected UTC 
2022/03/29 02:31:57 ch: ClickHouse server uses timezone="Asia/Shanghai", expected UTC
[root@fluent-bit-clinet-server uptrace]# 
[root@fluent-bit-clinet-server uptrace]# 
[root@fluent-bit-clinet-server uptrace]#

**Comment by vmihailenco** [comment]
Please see https://clickhouse.uptrace.dev/guide/getting-started.html#server-timezone . I will try to improve that in the next version.

**Comment by bruse-peng** [comment]
i change the time zone below but still error, if it is the reason of my os timezone
 

    <timezone>UTC</timezone>

**Comment by vmihailenco** [comment]
>i change the time zone below but still error, if it is the reason of my os timezone

It should not depend on the OS timezone. Perhaps you need to restart ClickHouse `sudo systemctl restart clickhouse-server`

>if convenient you can privide the chinese document ,by the way,the Author of uptrace come from USA?

I am from Moldova/Eastern Europe.

**Comment by vmihailenco** [comment]
I've some basic info you've requested at https://get.uptrace.dev/guide/intro.html. Please take a look.

**Comment by bruse-peng** [comment]
> > i change the time zone below but still error, if it is the reason of my os timezone
> 
> It should not depend on the OS timezone. Perhaps you need to restart ClickHouse `sudo systemctl restart clickhouse-server`
> 
> > if convenient you can privide the chinese document ,by the way,the Author of uptrace come from USA?
> 
> I am from Moldova/Eastern Europe.

i have restart clickhouse  but it still  has errors

[root@fluent-bit-clinet-server uptrace]# 
[root@fluent-bit-clinet-server uptrace]# uptrace --config=uptrace.yml ch reset
[ch]  09:54:47.312   CREATE TABLE          3.195ms  CREATE TABLE IF NOT EXISTS ch_migrations (name String, group_id Int64, migrated_at DateTime, sign Int8) Engine = CollapsingMergeTree(sign) ORDER BY (name)        *errors.errorString: ch: ClickHouse server uses timezone="Asia/Shanghai", expected UTC 
2022/03/29 09:54:47 ch: ClickHouse server uses timezone="Asia/Shanghai", expected UTC

**Comment by vmihailenco** [comment]
Please try v0.2.11 - it should work with any ClickHouse timezone.

**Comment by bruse-peng** [comment]
> Please try v0.2.11 - it should work with any ClickHouse timezone.

![image](https://user-images.githubusercontent.com/47881861/160749176-405e6b76-210c-4c46-a441-80ae74f676c7.png)

which version

**Comment by bruse-peng** [comment]
> Please try v0.2.11 - it should work with any ClickHouse timezone.

i update the uptrace.yml from host: 'localhost'  to host: '192.168.240.100' how should i restart uptrace, the ducument only privide   ./uptrace --config=uptrace.yml serve

**Comment by bruse-peng** [comment]
i killed process but it start again
![image](https://user-images.githubusercontent.com/47881861/160750687-89f4bdd8-6acb-4ff7-bfc7-36ff508a66c1.png)

**Comment by bruse-peng** [comment]
> Please try v0.2.11 - it should work with any ClickHouse timezone.

thank you it works,but if i want put django running metric to uptrace what should i do ,if i use elastic apm ,the document(https://www.elastic.co/guide/en/apm/get-started/current/install-and-run.html) tell me what should i do 
![image](https://user-images.githubusercontent.com/47881861/160751217-e2d7e78c-0069-411b-8825-7bea91a3b1c7.png)

**Comment by bruse-peng** [comment]
you should add the time range,1min,5min,15min,3min

**Comment by bruse-peng** [comment]
you should add the time range,1min,5min,15min,3min
![image](https://user-images.githubusercontent.com/47881861/160761249-3d83f551-3eb2-4df3-8ece-e73b448f3eaf.png)

**Comment by vmihailenco** [comment]
>i want put django

See [Django tutorial](https://get.uptrace.dev/opentelemetry/django.html)

>you should add the time range,1min,5min,15min,3min

I've added 15m and 30m periods. Smaller periods are not that useful because spans are buffered on all stages.
