### ISSUE TITLE
Planning v1.6 release

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/uptrace#235]
- https://github.com/uptrace/uptrace/issues/226
- https://github.com/uptrace/uptrace/issues/225
- https://github.com/uptrace/uptrace/issues/202
- https://github.com/uptrace/uptrace/issues/188
- https://github.com/uptrace/uptrace/issues/236
- https://github.com/uptrace/uptrace/issues/237

Feel free to suggest your issues :+1:

**Comment by gedw99** [comment]
any chance we can refactor out the go mod using

```sh
replace github.com/segmentio/encoding => github.com/vmihailenco/encoding v0.3.4-0.20220121071420-f96fbbb25975
```

**Comment by vmihailenco** [comment]
I can use `github.com/vmihailenco/encoding` directly if that helps.

**Comment by gedw99** [comment]
> @gedw99 I can use `github.com/vmihailenco/encoding` directly if that helps.

Yep that’s what I was hoping .

**Comment by jasonhu** [comment]
hi

commit https://github.com/uptrace/uptrace/commit/26a208bf252b78a3f9d5bd6484aa316b472bc818 have not merge to master branch now.

thanks.

**Comment by vmihailenco** [comment]
@jasonhu I had to remove Grafana integration, because it conflicts with https://uptrace.dev/get/ingest/prometheus.html

Later I will try to check what our options are to have both Prometheus and Grafana...

**Comment by vmihailenco** [comment]
@jasonhu Grafana tempo API is brought back in v1.6.0-rc1.

**Comment by rgl** [comment]
Since this issue is now closed, maybe it should be unpinned from the https://github.com/uptrace/uptrace/issues page.

**Comment by vmihailenco** [comment]
@rgl done, v1.6 was release some time ago.
