### ISSUE TITLE
sentry reporting with python sdk does not work

### ISSUE THREAD

**Issue by krombel** [uptrace/uptrace#238]
As Sentry-API got implemented (#83) I tried to send sentry logs to uptrace from a python app.

This fails on the server with:
`[bunrouter] [...] 400        593µs   POST     /api/2/store/          *json.UnmarshalTypeError: json: cannot unmarshal "{\"values\":[]},\"transaction_info\"..." into Go struct field tracing.SentryEvent.breadcrumbs of type []tracing.SentryBreadcrumb`

Szenario:
I have no control over the sources (so cannot implement another instrumentation) but the software allows exporting to sentry.

Versions:
- uptrace 1.5.0
- sentry-sdk 1.25.1

**Comment by vmihailenco** [comment]
This should be fixed in v1.5.1. Thanks for reporting.

**Comment by krombel** [comment]
I can confirm it is working now. Thanks 🙂
