### ISSUE TITLE
Alerts sent via alertmanager channel wrongly resolve after 5 minutes.

### ISSUE THREAD

**Issue by ttaghavi** [uptrace/uptrace#241]
Using uptrace 1.5 docker image.

I configured the following monitor in uptrace, with alertmanager as notification channel:

![uptrace_monitor](https://github.com/uptrace/uptrace/assets/1927275/4a84d216-ff16-4e5e-80f6-e4b1f1b7af46)

Which correctly triggers the following alert in uptrace:

![uptrace_alert](https://github.com/uptrace/uptrace/assets/1927275/c6e30bd2-5654-4720-a425-e6f883e4442d)

This creates the following alert in alertmanager:

![alertmanager_alerts](https://github.com/uptrace/uptrace/assets/1927275/b84aae75-120f-45d3-b2c2-dcd1cd261527)

We have alertmanager setup to send notifications to telegram. This also works, but after exactly 5 minutes, the alert is marked as "resolved" by alertmanager. Even though the trigger condition is still met (load above threshold).

![telegram_notification](https://github.com/uptrace/uptrace/assets/1927275/a0c191f3-48ad-45b7-ba3b-418bf1f58373)

The alert disappears from the alertmanager UI but is still present on the uptrace UI.

**Comment by vmihailenco** [comment]
```
# ResolveTimeout is the default value used by alertmanager if the alert does
  # not include EndsAt, after this time passes it can declare the alert as resolved if it has not been updated.
  # This has no impact on alerts from Prometheus, as they always include EndsAt.
  [ resolve_timeout: [<duration>](https://prometheus.io/docs/alerting/latest/configuration/#duration) | default = 5m ]
```

For now, you can bump the `ResolveTimeout` to a bigger value like 3 days.

In future, Uptrace will probably include `EndsAt`, but I need to check what Prometheus does in this case.

**Comment by vmihailenco** [comment]
We now set EndsAt for Prometheus: https://github.com/uptrace/uptrace/commit/76c0a8c8dde1c84803d214f50c79fbe271125aca. It is not quite what AlertManagers expects from us, but this will do for now.
