### ISSUE TITLE
Disable Username:Password Authentication

### ISSUE THREAD

**Issue by invaderb** [uptrace/uptrace#244]
Greetings,

I was looking through the code but didn't seem to see a way to disable username and password authentication even though I have SSO setup and working just wanted to see if there was a config available 

On a similar note it would be nice to have automatic redirection if a user isn't authenticated with SSO.

**Comment by vmihailenco** [comment]
Hello,

I would assume that having 0 configured users should not allow anyone to authentication using `user:pass`. Would that work fo you?

**Comment by invaderb** [comment]
@vmihailenco yeah I removed all the users in the yml config but was looking more about completely hiding the username and password fields

**Comment by haimgel** [comment]
> I removed all the users in the yml config 

In my testing, this is not sufficient (which is a separate footgun, tbh). The users get imported into the Postgres DB, and are still available for login after they are removed from the YML config. This is especially troubling because the default user gets created when no other users are configured, and the only way to get rid of it is to edit the database manually.

**Comment by invaderb** [comment]
> In my testing, this is not sufficient (which is a separate footgun, tbh). The users get imported into the Postgres DB, and are still available for login after they are removed from the YML config. This is especially troubling because the default user gets created when no other users are configured, and the only way to get rid of it is to edit the database manually.

oooh yeah that's pretty concerning

**Comment by vmihailenco** [comment]
>and are still available for login after they are removed from the YML config

Sounds like we need to ignore the database when authenticating users.

**Comment by vmihailenco** [comment]
This should be fixed in v1.5.2. The login form will still be visible, but none will be able to log in using it.
