### ISSUE TITLE
Not seeing span status description

### ISSUE THREAD

**Issue by QHQuach** [uptrace/uptrace#248]
In the Uptrace Community Edition, for the span with error, I only see the error icon/marking (with "span.status_code = 'error'" tooltip). Any idea where would the status_description can be seen?

I debug out the signal content through the collector and do see the status description being set/sent aside from the status error. Maybe there is an explicit tag has to be set for Uptrace? I tried to event explicitly set otel.status_description tag on the span but not visible either.

**Comment by vmihailenco** [comment]
Hello,

This should be fixed in v1.5.3. You should see the description when hovering on the status code.
