### ISSUE TITLE
Disable uptrace-go with config

### ISSUE THREAD

**Issue by hiimdoublej-swag** [uptrace/uptrace#250]
Hello there, I'd like to suggest a feature request for the embedded `uptrace-go`.
Right now there's no option from the uptrace side to turn it off directly, it would be beneficial for the end users to turn it off by config so that the resources are more dedicated to the spans and metrics that the user wanted to track with Uptrace.

**Comment by vmihailenco** [comment]
Should be fixed v1.5.6. You can add `disabled: true` to the config.

**Comment by hiimdoublej-swag** [comment]
> Should be fixed v1.5.6. You can add `disabled: true` to the config.

Great ! I'll try it out ! Thanks.
