### ISSUE TITLE
Failure to run on Clickhouse clusters with hyphens in a name

### ISSUE THREAD

**Issue by singler** [uptrace/uptrace#253]
Uptrace is failing to run migrations (can be workarounded) and run on Clickhouse clusters with a hyphen in a name, e.g. `logging-test`.

Migrations fail because `ON CLUSTER` query does not quote the cluster name, and having unquoted hyphen there causes syntax error. This can be workarounded by specifying cluster name with single quotes in config, e.g. `cluster: "'logging-test'"`

After migrations complete, Uptrace fails to run with
```
2023-09-01T11:43:01.840Z	info	uptrace/main.go:117	starting Uptrace...	{"version": "v1.5.5", "config": "/etc/uptrace/uptrace.yml"}
initClickhouse failed: can't find "'logging-test'" cluster in system.clusters (try to reset database)
```

**Comment by vmihailenco** [comment]
Should be fixed in master.
