### ISSUE TITLE
paginated data are not properly sorted

### ISSUE THREAD

**Issue by singler** [uptrace/uptrace#260]
Hello,
when viewing data with multiple pages, it's not being properly sorted, e.g. first page could be 8 to 0.02 of a value, and on the second page you could find higher values again and again. E.g.:
<img width="1076" alt="image" src="https://github.com/uptrace/uptrace/assets/813638/12988c7b-7dac-48fe-b4a7-34af04dd97db">
<img width="1011" alt="image" src="https://github.com/uptrace/uptrace/assets/813638/75d98970-f1a9-4ae3-bd52-1c2bbc60fc62">
<img width="962" alt="image" src="https://github.com/uptrace/uptrace/assets/813638/110f52c5-340b-4fc8-a2f3-7e22cc95f848">
and it seems that cloud demo is not affected by this

**Comment by singler** [comment]
UI paginates the data by the order in which it was received in a response and then sorts it inside the the page. This changes partially fixes it by returning data in sorted order:
```
diff --git a/pkg/tracing/span_filter.go b/pkg/tracing/span_filter.go
index bc7369a..8e82535 100644
--- a/pkg/tracing/span_filter.go
+++ b/pkg/tracing/span_filter.go
@@ -144,6 +144,9 @@ func buildSpanIndexQuery(
        app *bunapp.App, f *SpanFilter, dur time.Duration,
 ) (*ch.SelectQuery, *orderedmap.OrderedMap[string, *ColumnInfo]) {
        q := NewSpanIndexQuery(app).Apply(f.whereClause)
+       if f.OrderByMixin.SortBy != "" {
+               q = q.Order(fmt.Sprintf("%s %s", f.OrderByMixin.SortBy, f.OrderByMixin.SortDir()))
+       }
        return compileUQL(q, f.parts, dur)
 }
```
but if you would change sort order on the column, you would still get changed sorting on that page, hitting "reload" would get data again for the new order.
It seems that proper fix would be to revamp UI side to resort already received data and then display them paginated

**Comment by vmihailenco** [comment]
@singler sounds like a plan. Could you send a PR? I can handle the UI part.

You probably also need to add this to the `SpanFilter.UnmarshalValues`:

```
	if err := f.OrderByMixin.UnmarshalValues(ctx, values); err != nil {
		return err
	}
```

**Comment by singler** [comment]
opened PR https://github.com/uptrace/uptrace/pull/267

**Comment by vmihailenco** [comment]
@singler thanks for fixing this!
