### ISSUE TITLE
Allow specifying BASE_URL in configuration

### ISSUE THREAD

**Issue by mderazon** [uptrace/uptrace#263]
Hello 👋🏼 
I am trying to use Uptrace mounted under a sub path, something like 
```
https://monitoring.mysite.com/uptrace/*
```
(As I am running it side by side with other tools, for example, `https://monitoring.mysite.com/grafana/*`)

The problem is that some of the URLs in the Uptrace frontend are hard coded to the absolute path, see for example:
https://github.com/uptrace/uptrace/blob/9c0cefe1434524b86aa5d6c62b79881bac43f623/vue/src/views/Login.vue#L147

It would be nice if the app would not rely on the absolute URL and use a BASE_URL configured by the user, something like
```ts
const url = `${BASE_URL}/api/v1/users/login` 
```
This will allow the app to be mounted on any sub path basically.

**Comment by mderazon** [comment]
@vmihailenco only case I found so far where it's still not fixed which is the SSO Google login button:
![Screenshot 2023-11-28 120744](https://github.com/uptrace/uptrace/assets/717076/3adde345-8d91-40ec-8f9a-721512007d9c)

(See the url in the bottom left, should be prefixed with `/uptrace/...`)

**Comment by vmihailenco** [comment]
@mderazon will fix, thanks.

**Comment by vmihailenco** [comment]
@mderazon we've tried to fix this but were not able to reproduce it. It looks like the URL on your screenshot should be already handled by Uptrace. Perhaps you were using an old version?
