### ISSUE TITLE
Error saving DashGauge with optional value mappings

### ISSUE THREAD

**Issue by stratdev3** [uptrace/uptrace#264]
In a DashGauge

![image](https://github.com/uptrace/uptrace/assets/115271718/654922a8-ad12-40e4-a539-c3c6c4365952)

Add some mappings values (example: red color when host.count < 3)

![image](https://github.com/uptrace/uptrace/assets/115271718/3d1be9f8-4ca6-4057-9ae0-f18490786101)

Saving result as an error
![image](https://github.com/uptrace/uptrace/assets/115271718/a0b91614-1592-4503-b9b1-5947e543671f)

Thanks

**Comment by vmihailenco** [comment]
This is fixed now. Thanks for reporting.
