### ISSUE TITLE
json name error in /pkg/tracing/zipkin_handler.go#L53C36-L53C36

### ISSUE THREAD

**Issue by jasonhu** [uptrace/uptrace#265]
https://github.com/uptrace/uptrace/blob/4cabd5b11bdbf1cc0edfa8ce95cd341200dc03c5/pkg/tracing/zipkin_handler.go#L53C36-L53C36

**Comment by vmihailenco** [comment]
Should be fixed by https://github.com/uptrace/uptrace/commit/87cebed4f65bff815e63a9b09368fb5ac9e30cf7
