### ISSUE TITLE
Error saving bar chart with custom color

### ISSUE THREAD

**Issue by smyrman** [uptrace/uptrace#271]
When trying to save using a custom color for a bar-chart, I get an error that something tries to Unmarshal a floating point number into an integer (lineWidth).

Using: uptrace.dev

A censored image of what happens when clicking save:

![image](https://github.com/uptrace/uptrace/assets/75205/93864d1d-93cc-43cf-9a89-d90e3fc9274c)

**Comment by vmihailenco** [comment]
@smyrman thanks for reporting. This should be fixed now.
