### ISSUE TITLE
Error when trying to sort the results by a non-existent field

### ISSUE THREAD

**Issue by anmic** [uptrace/uptrace#278]
[screencast-local.uptrace.com_19876-2023.10.12-19_40_25.webm](https://github.com/uptrace/uptrace/assets/3912070/28a55f6e-ebe4-45dc-975e-1ea5aaabd7b8)

*ch.Error: DB::Exception: Missing columns: '.count_per_min' while processing query: 'SELECT group_id AS `.group_id`, sum(count) AS `.count`, sumIf(count, status_code = 'error') AS `.error_count`, quantileTDigest(0.5)(toFloat64OrDefault(duration)) AS `p50(.duration)`, quantileTDigest(0.9)(toFloat64OrDefault(duration)) AS `p90(.duration)`, quantileTDigest(0.99)(toFloat64OrDefault(duration)) AS `p99(.duration)`, sum(toFloat64OrDefault(duration)) AS `sum(.duration)`, any(system) AS `.system`, any(display_name) AS `display.name` FROM spans_index AS s WHERE (project_id = 1) AND (time >= toDateTime('2023-10-12 14:42:10', 'UTC')) AND (time < toDateTime('2023-10-12 15:42:10', 'UTC')) AND (type NOT IN ('log', 'message', 'other-events')) AND (trace_id = '178d64dbf42b1028caee5c06aeb8372b') GROUP BY `.group_id` ORDER BY `.count_per_min` DESC LIMIT 1000', required columns: 'group_id' 'time' 'project_id' 'type' 'status_code' 'trace_id' '.count_per_min' 'system' 'count' 'duration' 'display_name', maybe you meant: 'group_id', 'time', 'project_id', 'type', 'status_code', 'trace_id', 'system', 'count', 'duration' or 'display_name'

 https://github.com/uptrace/uptrace/blob/master/vue/src/tracing/use-explore-spans.ts#L41
 
 Сreates the following API request:
 http://local.uptrace.com:19876/api/v1/tracing/1/groups?time_gte=2023-10-12T14:42:10.000Z&time_lt=2023-10-12T15:42:10.000Z&query=where+.trace_id+%3D+178d64dbf42b1028caee5c06aeb8372b+%7C+group+by+.group_id+%7C+.count+%7C+.error_count+%7C+%7Bp50,p90,p99,sum%7D(.duration)&system[]=spans:all&sort_by=.count_per_min&sort_desc=true&search=
 
```
SELECT
  s."group_id" AS ".group_id",
  sum(s.count) AS ".count",
  sumIf (s.count, s.status_code = 'error') AS ".error_count",
  quantileTDigest (0.5) (toFloat64OrDefault (s."duration")) AS "p50(.duration)",
  quantileTDigest (0.9) (toFloat64OrDefault (s."duration")) AS "p90(.duration)",
  quantileTDigest (0.99) (toFloat64OrDefault (s."duration")) AS "p99(.duration)",
  sum(toFloat64OrDefault (s."duration")) AS "sum(.duration)",
  any (s."system") AS ".system",
  any (s."display_name") AS "display.name"
FROM
  "spans_index" AS s
WHERE
  (s.project_id = 1)
  AND (
    s.time >= toDateTime ('2023-10-12 14:45:00', 'UTC')
  )
  AND (
    s.time < toDateTime ('2023-10-12 15:45:00', 'UTC')
  )
  AND (
    (s.type NOT IN ('log', 'message', 'other-events'))
  )
  AND (s."trace_id" = '178d64dbf42b1028caee5c06aeb8372b')
GROUP BY
  ".group_id"
ORDER BY
  ".count_per_min" desc
LIMIT
  1000
 ```

**Comment by vmihailenco** [comment]
Should be fixed in master.
