### ISSUE TITLE
1.5.9 broke spans_index_buffer_dist usage

### ISSUE THREAD

**Issue by singler** [uptrace/uptrace#279]
in distributed and sharded setup 1.5.9 errors out on not found table `spans_index_dist`. Previous versions work fine with such cluster setup.
<img width="499" alt="image" src="https://github.com/uptrace/uptrace/assets/813638/6d628450-300e-4c7b-9467-8283ba44d6d5">

I would think that this commit https://github.com/uptrace/uptrace/commit/0307ec8f34f669c8753329ad447c8df2d7b3c4a9 introduced the breaking change by stopping using buffer table and not introducing migration to create a dist table for spans_index. 

This change also mentions `spans_data_stub` table which I think also will not be created?

**Comment by vmihailenco** [comment]
Not querying the buffer table is the right thing since each replica has a separate buffer which causes some other issues.

Try to create the missing table:

```sql
CREATE TABLE spans_index_dist ON CLUSTER uptrace1 AS spans_index_buffer
ENGINE = Distributed(uptrace1, currentDatabase(), spans_index, rand())
```

>This change also mentions spans_data_stub table which I think also will not be created?

It is not a real table and is not used anywhere.

**Comment by singler** [comment]
> Not querying the buffer table is the right thing since each replica has a separate buffer which causes some other issues.
> 
what issues does it cause, if I may ask?

> Try to create the missing table:
> 
> ```sql
> CREATE TABLE spans_index_dist ON CLUSTER uptrace1 AS spans_index_buffer
> ENGINE = Distributed(uptrace1, currentDatabase(), spans_index, rand())
> ```
> 
I works when created manually, but I imagine at some point it should be fixed in code too as other dist tables are created automatically

**Comment by vmihailenco** [comment]
This should be fixed in master.

>what issues does it cause, if I may ask?

It is not supported in the community edition, but in k8s when you have multiple replicas the query goes to a random replica. So some replicas will have more data than the others and when reading from the buffer table users will see 404 errors.
