### ISSUE TITLE
read project list from a dynamic source (feature request)

### ISSUE THREAD

**Issue by dixanms** [uptrace/uptrace#28]
Feature request: Read the project list periodically from a dynamic source such as a URL, or from the output of a script.

Currently, a reconfiguration and a service restart is required, which is not ideal for complex environments

**Comment by vmihailenco** [comment]
We could add a function that returns a [list of projects](https://github.com/uptrace/uptrace/blob/master/pkg/org/project.go) as a single source of truth and then use that list everywhere.

PR is welcome.
