### ISSUE TITLE
Close Alerts error.

### ISSUE THREAD

**Issue by pnvasko** [uptrace/uptrace#289]
Hi, when i try close Alert, get 3 500 error:
API end point: /internal/v1/projects/1/alerts/closed
![Screenshot from 2023-11-15 05-04-08](https://github.com/uptrace/uptrace/assets/12684928/7e490549-7f29-4e4f-bfb5-62faad900122)

**Comment by vmihailenco** [comment]
This was fixed in v1.6.0-rc.1, but the database was not reset properly. Try to upgrade to v1.6.0-rc.2 and run:

```shell
uptrace pg reset
```
