### ISSUE TITLE
Error sorting by wrong column span.count_per_min

### ISSUE THREAD

**Issue by dixanms** [uptrace/uptrace#29]
http://oteldev-01.moncc.net:14318/explore/13385337/spans?time_dur=3600&query=group%20by%20span.group_id%20%7C%20span.count_per_min%20%7C%20span.error_pct%20%7C%20%7Bp50,p90,p99%7D%28span.duration%29%20%7C%20where%20span.group_id%20%3D%20%228962033991366417035%22&system=http%3Aotel-ui-dev&sort_by=span.count_per_min&sort_dir=desc

`*ch.Error: DB::Exception: Missing columns: 'span.count_per_min' while processing query: 'SELECT `span.id`, `span.trace_id` FROM spans_index_buffer AS s WHERE (project_id = 13385337) AND (`span.time` >= toDateTime('2022-04-15 20:29:00', 'UTC')) AND (`span.time` < toDateTime('2022-04-15 21:29:00', 'UTC')) AND (`span.system` = 'http:otel-ui-dev') AND (`span.group_id` = '8962033991366417035') ORDER BY `span.count_per_min` DESC LIMIT 10', required columns: 'span.id' 'span.trace_id' 'project_id' 'span.time' 'span.system' 'span.count_per_min' 'span.group_id', maybe you meant: ['span.id','span.trace_id','project_id','span.time','span.system','span.group_id']`

![image](https://user-images.githubusercontent.com/2984717/163635333-ff1bfba0-026f-4c10-a23f-e50b6db93ff7.png)

![image](https://user-images.githubusercontent.com/2984717/163635205-cb74b1b5-fc91-4138-8ade-6ac987a57b80.png)

**Comment by vmihailenco** [comment]
This was fixed in v0.2.13. Can you make sure you have the last version? https://get.uptrace.dev/guide/debugging.html

**Comment by vmihailenco** [comment]
Indeed, sorry :man_shrugging:
