### ISSUE TITLE
how to show span event name in uptrace console website

### ISSUE THREAD

**Issue by yundiz** [uptrace/uptrace#300]
hi,
  i  add span with 2 events.  and each event  with name, but i open span and switch to event tab in console website.
i just find the event time without name, how to config show it.

**Comment by vmihailenco** [comment]
Seems to be working here
![2023-12-19_12-30](https://github.com/uptrace/uptrace/assets/290976/cd480530-b4f0-4510-bbbc-c69017283bbc)

Can't tell more without a clean description how to reproduce the issue.
