### ISSUE TITLE
Wrong unit in title in service graphs between services.

### ISSUE THREAD

**Issue by rattuscz** [uptrace/uptrace#310]
It seems the service graphs show wrong unit for time spent on calls -> example:
![image](https://github.com/uptrace/uptrace/assets/688332/9fc98593-f8cd-4c90-978a-62fc77aff300)

the 1.5ms is correct there.

Or is the title next to line showing different metric?

**Comment by vmihailenco** [comment]
Thanks for reporting. This should be fixed in the next minor release.
