### ISSUE TITLE
node_exporter data display fails

### ISSUE THREAD

**Issue by QuanZi123** [uptrace/uptrace#312]
On the Dashboards page, the monitoring data collected through prometheus is displayed correctly on an hourly basis, but fails on a daily basis
uptrace version:  v1.6.1
![24h](https://github.com/uptrace/uptrace/assets/142292346/45c9ea51-6e09-4f0e-929c-8f628cd0d138)
![3d](https://github.com/uptrace/uptrace/assets/142292346/97a9fab5-1d40-4361-bf5d-12ffa0b4fa66)

**Comment by QuanZi123** [comment]
@vmihailenco

**Comment by vmihailenco** [comment]
This seems to work in the Cloud version so it is probably some subtle bug in the Community edition. I will take look a closer look at this in a few days.

**Comment by vmihailenco** [comment]
@QuanZi123 this should be fixed in v1.6.2 which will be released shortly.

**Comment by QuanZi123** [comment]
@vmihailenco
Gauges still no data，
![0](https://github.com/uptrace/uptrace/assets/142292346/7e6f9493-59ef-44e9-be89-c0f87bd9661e)

**Comment by vmihailenco** [comment]
@QuanZi123 this should be fixed in the next minor release.
