### ISSUE TITLE
*ch.Error: DB::Exception: Cannot convert string undefined to type UInt64

### ISSUE THREAD

**Issue by JohnBat26** [uptrace/uptrace#315]
Hi.
When I try to show slow span in dashboard: `Uptrace: spans by service`  I got 404 and this in logs:

``
[ch]  15:55:19.214   SELECT                6.192ms  SELECT groupArray(count) AS count, groupArray(rate) AS rate, groupArray(time_) AS time FROM (SELECT s."group_id" AS "_group_id", sum(s.count) / 60 AS "per_min(_count)", sumIf(s.count, s.status_code = 'error') / sum(s.count) AS "_error_rate", quantileTDigest(0.5)(s."duration") AS "p50(_duration)", quantileTDigest(0.9)(s."duration") AS "p90(_duration)", quantileTDigest(0.99)(s."duration") AS "p99(_duration)", any(s."system") AS "_system", any(s."display_name") AS "display_name", sum(s.count) AS count, sum(s.count) / 1 AS rate, toStartOfInterval(s.time, INTERVAL 1 minute) AS time_ FROM "spans_index" AS "s" WHERE (s.project_id = 1) AND (s.time >= toDateTime('2024-01-22 11:56:00', 'UTC')) AND (s.time < toDateTime('2024-01-22 12:56:00', 'UTC')) AND (s."group_id" = 'undefined') AND (s.project_id = 1) AND (s.time >= toDateTime('2024-01-22 11:56:00', 'UTC')) AND (s.time < toDateTime('2024-01-22 12:56:00', 'UTC')) GROUP BY "_group_id", time_ ORDER BY time_ ASC LIMIT 10000) GROUP BY tuple() LIMIT 1000           *ch.Error: DB::Exception: Cannot convert string undefined to type UInt64: while executing 'FUNCTION equals(group_id : 1, 'undefined' : 8) -> equals(group_id, 'undefined') UInt8 : 12' (53) 
[bunrouter]  15:55:19.206  17acac9605a57f42736254dbcd1add1d   500      8.557ms   GET      /internal/v1/tracing/1/percentiles?time_gte=2024-01-22T11:56:00.000Z&time_lt=2024-01-22T12:56:00.000Z&query=group+by+_group_id+%7C+per_min(_count)+%7C+_error_rate+%7C+%7Bp50,p90,p99%7D(_duration)+%7C+where+_group_id+%3D+undefined      *ch.Error: DB::Exception: Cannot convert string undefined to type UInt64: while executing 'FUNCTION equals(group_id : 1, 'undefined' : 8) -> equals(group_id, 'undefined') UInt8 : 12' (53) 
``

**Comment by vmihailenco** [comment]
The query you've provided does not seem to be related to dashboards/metrics and I can't reproduce it. Please try to upgrade to the latest version and re-open the issue with clearer instructions.
