### ISSUE TITLE
CHANGELOG.md not updating

### ISSUE THREAD

**Issue by jgkawell** [uptrace/uptrace#316]
Since v1.6.0 was released it doesn't appear that the `CHANGELOG.md` file is being updated on release. Neither v1.6.1 nor v1.6.2 have entries in the file. Is something wrong with the release action?

**Comment by vmihailenco** [comment]
I update the changelog manually and usually it is not updated since there are no big changes in minor releases. There is a big one in v1.6.2 regarding metrics and I will document it soon.

**Comment by vmihailenco** [comment]
Done: https://github.com/uptrace/uptrace/blob/master/CHANGELOG.md#v162---january-22-2024
