### ISSUE TITLE
Overview slowest max(_duration) not max(_time)

### ISSUE THREAD

**Issue by stratdev3** [uptrace/uptrace#318]
Hi,

It seems there is a change in the previous releases.

Before, in the Overview > Slowest nav we can see the `max(_duration)` metric and it makes sense to get the value of the slowest.

Now, in this slowest the `max(_time)` is shown and is absolutely irrelevant compared to `max(duration)`.

Maybe a regression ?

![uptr](https://github.com/uptrace/uptrace/assets/115271718/5548b2c9-2957-4e1b-88de-76914c06c131)

Thanks for your lights

**Comment by vmihailenco** [comment]
This is a bug. Thanks for reporting.

**Comment by vmihailenco** [comment]
This should be fixed now.
