### ISSUE TITLE
Attributes dropdown checkbox in metrics page is not useful (UI bug)

### ISSUE THREAD

**Issue by smunukutla-mycarrier** [uptrace/uptrace#320]
The checkbox in the dropdown for selecting attributes under metrics (shown in the screen-recording below) is not functional. Clicking on the checkbox doesn't select the attribute. To select the attribute, you'd have to click on the text next to the checkbox. This is not by any means a priority item but definitely a UI bugfix that might help in improving user experience.

Uptrace version: v1.6.2

https://github.com/uptrace/uptrace/assets/149697415/e14f813d-5de1-417b-b0e4-1d185bd843bd

**Comment by vmihailenco** [comment]
Thanks for reporting. This should be fixed in the next minor release.
