### ISSUE TITLE
Calculate Availability from httpcheck

### ISSUE THREAD

**Issue by stratdev3** [uptrace/uptrace#321]
Hi,

i've setup an `httpcheck` with multiple endpoints in the `receivers` section of my otelcol-contrib.yaml. Everything show up in uptrace.

Now i'm looking for a specific column to calculate the availability (in red) of each endpoint ?

![2024-01-27 00_12_49-Window](https://github.com/uptrace/uptrace/assets/115271718/e37f3b66-4667-4845-bcc6-031168aaf92a)

Also, i've tried to add column/formula to calculate this.
One thing i don't understand is : despite the fact i set `sum()` the `table value` override.

![image](https://github.com/uptrace/uptrace/assets/115271718/bdd400f4-ee0c-4ba3-b534-caf05307c0bb)

if i change table value to `sum of value`, then it works.

![image](https://github.com/uptrace/uptrace/assets/115271718/44233a54-64aa-4619-bec6-cbc0920fd44f)

thanks for your lights

**Comment by vmihailenco** [comment]
The `sum($metric)` expression is used to query a timeseries for a sparkline. The "Table value" function is then used to calculate a table value from the timeseries.

**Comment by vmihailenco** [comment]
You should be able to calculate the availability using the `sum($status{http_response_status_class="2xx"}) / sum($status) as availability` expression after upgrading to the next minor version. The existing template should be updated automatically, but you can also do it manually by clicking "Reset dashboard from template" in the dashboard menu.

**Comment by stratdev3** [comment]
Thanks for your complete answer
