### ISSUE TITLE
Rollup not working over explicit interval

### ISSUE THREAD

**Issue by arend-melissant-tnt** [uptrace/uptrace#332]
Using sum_over_time($var) works when using an implicit time interval, but an explicit time interval gives me an error when trying to configure it:

When using sum_over_time($var[15m])

It gives an error

unexpected "sum_over_time"

But this should work according to the documentation 

I am using self hosted v1.6.3

**Comment by vmihailenco** [comment]
Thanks for reporting. This should be fixed in the master branch.
