### ISSUE TITLE
Docker example metrics_from_spans metric name dots vs underscores

### ISSUE THREAD

**Issue by rgl** [uptrace/uptrace#341]
The following example uses the metric name with dots `uptrace.tracing.spans` : 

https://github.com/uptrace/uptrace/blob/bef48584da59d7f3acffa7ddb82682b1212b839a/example/docker/uptrace.yml#L85

But the example below it, uses the metric name with underscores `uptrace_tracing_events`:

https://github.com/uptrace/uptrace/blob/bef48584da59d7f3acffa7ddb82682b1212b839a/example/docker/uptrace.yml#L100

Can those be normalized to either use underscores or dots?

I'm not sure which should be used thou. I'm not yet familiar with the conventions, and would appreciate guidance on that.

**Comment by vmihailenco** [comment]
They both should use underscores to be compatible with Prometheus. I will fix it, thanks for reporting.
