### ISSUE TITLE
Rust `with_max_queue_size` is gone in v0.22

### ISSUE THREAD

**Issue by frederikhors** [uptrace/uptrace#352]
With latest Rust's crate `opentelemetry_sdk` v0.22 `with_max_queue_size` is not there anymore.

To fix docs in https://uptrace.dev/get/opentelemetry-rust.html

This is the reason: https://github.com/open-telemetry/opentelemetry-rust/pull/1480.

**Comment by vmihailenco** [comment]
The instructions should be fixed. Thanks for reporting.
