### ISSUE TITLE
No error monitor

### ISSUE THREAD

**Issue by Arend-melissant** [uptrace/uptrace#356]
It seems that the error monitor is not working, I don't get any alerts, though there are error logs coming in.
I also notice that the 'uptrace_tracing_logs' metric can't be found, trying to add that as a metric monitor gives me a 'metric not found, even if I add it through the error detail 'monitor' button.

**Comment by vmihailenco** [comment]
I need more details like what version are you using and what error logs are coming. It would help if you can reproduce it with the Cloud version.

>notice that the 'uptrace_tracing_logs' metric can't be found

This is a system metric which is only present in v1.7.0-rc.1+. Until that version you were supposed to [create](https://uptrace.dev/get/span-metrics.html) it yourself.

**Comment by Arend-melissant** [comment]
Ok,

I'm using 1.7 beta, so that explains it

Thanks for the feedback

**Comment by vmihailenco** [comment]
I guess this can be closed then.
