### ISSUE TITLE
Missing Column Error in ClickHouse Database

### ISSUE THREAD

**Issue by wowi42** [uptrace/uptrace#361]
# Environment

    - Uptrace Version: 1.7.1
    - Database: ClickHouse 23.7.1.214
    - Error Occurrence: During data insertion into the database

# Description

While launching uptrace 1.7.1 as a docker container, we are seeing this message on logs. the Clickhouse DB was created for this version of uptrace

[ch]  07:56:49.854   INSERT                1.969ms  INSERT INTO "datapoint_minutes_buffer" ("project_id", "metric", "instrument", "time", "attrs_hash", "min", "max", "sum", "count", "gauge", "histogram", "string_keys", "string_values", "otel_library_name", "otel_library_version") VALUES 	  *ch.Error: DB::Exception: No such column otel_library_name in table uptrace_17.datapoint_minutes_buffer (41053376-95bb-4695-90e3-7265e35b15f5) 

# Additional Information

- This issue might involve a discrepancy between the database schema expected by Uptrace and the schema currently implemented in ClickHouse.
- It may be useful to review any recent changes to the database schemas or related application updates.

**Comment by vmihailenco** [comment]
Here is the migration file: https://github.com/uptrace/uptrace/blob/master/pkg/bunapp/chmigrations/20240305130047_otel_lib.up.sql

You can try to apply it manually or reset the ClickHouse database: https://uptrace.dev/get/debugging.html
