### ISSUE TITLE
feature for uptrace to be set as remote read for prometheus

### ISSUE THREAD

**Issue by kost2191** [uptrace/uptrace#364]
Hello, I'm trying to set uptrace as a remote-read for prometheus:
```remote_read:
- url: http://my-uptrace.uptrace.svc.cluster.local:14318/api/v1/prometheus/read
  remote_timeout: 30s
  headers:
    uptrace-dsn: http://secret@my-uptrace.uptrace.svc.cluster.local:14318?grpc=14317
  follow_redirects: true
  enable_http2: true
  filter_external_labels: true
  ```
  
  But this leads to this error when quering graph from prometheus:
  `remote_read: remote server http://my-uptrace.uptrace.svc.cluster.local:14318/api/v1/prometheus/read returned HTTP status 500 Internal Server Error: {"error":{"status":500,"code":"internal","message":"*ch.Error: DB::Exception: Missing columns: 'sum' 'time' 'value' 'instrument' 'd.string_keys' 'd.string_values' 'm.string_keys' 'metric' 'm.time' 'm.string_values' 'm.metric' while processing query: 'SELECT m.metric, m.string_keys, m.string_values, multiIf(instrument = 'additive', argMax(value, time), instrument = 'counter', sumWithOverflow(sum), instrument = 'gauge', avg(value), -1) AS value, toStartOfInterval(m.time, toIntervalSecond(60)) WHERE (m.time \u003e= toDateTime(1713514207)) AND (m.time \u003c toDateTime(1713528000)) AND (metric = 'up') AND ((d.string_values[indexOf(d.string_keys, 'cluster_name')]) = 'aw-prod') AND ((d.string_values[indexOf(d.string_keys, 'consul_dc')]) = 'aw') AND ((d.string_values[indexOf(d.string_keys, 'prometheus')]) = 'kube-system/prometheus-operator-prometheus')', required columns: 'm.metric' 'm.string_values' 'm.time' 'metric' 'm.string_keys' 'd.string_values' 'd.string_keys' 'instrument' 'value' 'time' 'sum' (47)"},"statusCode":500,"traceId":"17c7b402caefbe05e05ad1068d92fdfa"}`
  
  Am I doing something wrong? Or it is not able to do like this using uptrace? 
  Will you add this ability?
  uptrace version:  uptrace/uptrace:1.7.0

**Comment by vmihailenco** [comment]
For the time being we don't have plans to add this feature to Uptrace.
