### ISSUE TITLE
must be an agg for uniq function

### ISSUE THREAD

**Issue by azat** [uptrace/uptrace#368]
I.e. the following query in logs shows an error - `must be an agg or a group-by`

```
uniq(display_name) | group by _group_id
```

![uptrace-1](https://github.com/uptrace/uptrace/assets/430798/6ab7319c-a4fe-4957-afa2-71bb0443901a)

Likely the problem is here - https://github.com/uptrace/uptrace/blob/0e3c4ea6bc6fc4ce646a1edb6072940541a98d5c/pkg/tracing/span_query.go#L332C6-L361

**Comment by vmihailenco** [comment]
This should be fixed in the master branch.

**Comment by azat** [comment]
Fixed in https://github.com/uptrace/uptrace/commit/a6b6a5e2d1e7bbf890b68d64ab51c74f1ea75dda
