### ISSUE TITLE
feat: support otel log natively with otel-go v1.26.0

### ISSUE THREAD

**Issue by sysulq** [uptrace/uptrace#375]
After this release, opentelemetry-go supports log natively.

Is there any plan to add support for this new feature? Thanks in advanced.

https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.26.0

**Comment by sysulq** [comment]
Seems like this issue should be requested in http://github.com/uptrace/uptrace-go ? 🙂

**Comment by sysulq** [comment]
@vmihailenco Good news! Here is the v1.27 release :-)
And I tried to use it directly in my kod framework, works well

- https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.27.0
- https://github.com/go-kod/kod/blob/main/examples/log/main.go

**Comment by vmihailenco** [comment]
Here you go: https://github.com/uptrace/uptrace-go/tree/master/example/slog
