### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by BandarenkaDaniil** [uptrace/uptrace#378]
There is minor typo in `OpenTelemetry Metrics API for Python` page in one of the section names

Actual: UpDownCounterOserver
Expected: UpDownCounterObserver
The same in the url

Link: https://uptrace.dev/opentelemetry/python-metrics.html#updowncounteroserver

**Comment by vmihailenco** [comment]
Thanks, this should be fixed on next deploy.
