### ISSUE TITLE
Problem with getting SMTP mailer to work using TLSOpportunistic.

### ISSUE THREAD

**Issue by oderwat** [uptrace/uptrace#379]
I try for hours to figure out how to configure V1.7.6 for use with "Postmark" which provides SMTP with STARTTLS on ports 25, 2525 and 587.

While another provider works well using port 465 (always TLS) I can't find a way to get it to work with STARTTLS.

But I think it should work by just giving the: host, port (587), user and password. 

From what I read in the code `conf.TLS` would nil and this should set up the TLSOpportunistic variant (see: https://github.com/uptrace/uptrace/blob/a5ba7faf1ae150699d11ceee28e9e96e79d5373b/pkg/alerting/notif_email.go#L52).

This seems strange to me, because I do want to have TLSMandatory and with STARTTLS (not using/needing a client certificate).

What I get is:

```
uptrace  | 2024-05-24T23:13:08.495Z     error   backend/log.go:25       job failed (will retry) {"task_name": "notify-by-email", "reserved_count": 5, "delay": 480, "error": "dial failed: tls: first record does not look like a TLS handshake"}
uptrace  | github.com/vmihailenco/taskq/v4/backend.Error
uptrace  |      github.com/vmihailenco/taskq/v4@v4.0.0-beta.4/backend/log.go:25
uptrace  | github.com/vmihailenco/taskq/v4.(*Consumer).release
...
```

When I look at this I sadly can't see where this error is originating from. But it looks like as if TLS is expected on Dial which is not how STARTTLS works. I wonder why the TLS config is set at all. Is STARTTLS supposed to work? Is this tested? I saw that using mailpit is a no TLS at all setup, which worked for me only after using `auth_type: ''`, which means "no auth".

P.S.: I may try to use "mail-go" in a small example myself as I do not really understand what is going on. Right now, I use the docker image of Uptrace and I am short with time, but I really need this to work.

**Comment by vmihailenco** [comment]
>I may try to use "mail-go" in a small example myself as I do not really understand what is going on. 

This is what I recommend as well to see what mail-go options you need.
