### ISSUE TITLE
Add usable healthcheck for Docker Compose

### ISSUE THREAD

**Issue by Galaf** [uptrace/uptrace#380]
Hello!

It seems that the example with docker-compose is fairly out of date and also does not work half the time, unfortunately.
From my own debugging, it lacks the `depends_on` attributes necessary to start components on time.

I was able to debug most of them but the last one needed is probably uptrace itself.

When `otel/opentelemetry-collector-contrib` starts, it outputs the following error:

```
otelcol-1     | 2024-05-31T15:07:17.974Z       warn    zapgrpc/zapgrpc.go:195  [core] [Channel #3 SubChannel #4] grpc: addrConn.createTransport failed to connect to {Addr: "uptrace:14317", ServerName: "uptrace:14317", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 172.31.0.10:14317: connect: connection refused"     {"grpc_log": true}
```

There is no way that I can tell to explicitly wait for uptrace to be fully started and only then starting the collector but it seems indeed.

Do you have a workaround or could you add something to make it possible, please?

**Comment by vmihailenco** [comment]
@Galaf I use a similar Docker compose config every day and it just works without any `depends_on`  clauses....

That said I will try to add `depends_on` where it makes sense.

>When otel/opentelemetry-collector-contrib starts, it outputs the following error:

This is a warning and Otel Collect will try to reconnect on a regular basis. It is unlikely to cause any issues.
