### ISSUE TITLE
otlp.uptrace.dev - 404 page not found

### ISSUE THREAD

**Issue by frederikhors** [uptrace/uptrace#385]
Today I'm getting `OpenTelemetry trace error occurred. OpenTelemetry trace export failed. Url: 404, Status Code: https://otlp.uptrace.dev/, Response: b"404 page not found\n"`.

Why?

**Comment by vmihailenco** [comment]
No ideas. How can I reproduce this?

**Comment by frederikhors** [comment]
Ok, I narrowed down the issue. If I upgrade these:

```diff
- opentelemetry = { version = "0.22.0", default-features = false, features = [
+ opentelemetry = { version = "0.23.0", default-features = false, features = [
    "trace",
] }
- opentelemetry-otlp = { version = "0.15.0", default-features = false, features = [
+ opentelemetry-otlp = { version = "0.16.0", default-features = false, features = [
    "http-proto",
    "reqwest-client",
    "reqwest-rustls",
] }
- opentelemetry_sdk = { version = "0.22", default-features = false, features = [
+ opentelemetry_sdk = { version = "0.23", default-features = false, features = [
    "rt-tokio",
] }
- tracing-opentelemetry = { version = "0.23.0", default-features = false }
+ tracing-opentelemetry = { version = "0.24.0", default-features = false }
```

I get the error:

`OpenTelemetry trace error occurred. HTTP status client error (404 Not Found) for url (https://otlp.uptrace.dev/)`.

Why?

**Comment by frederikhors** [comment]
I opened this too: https://github.com/open-telemetry/opentelemetry-rust/issues/1866.

**Comment by vmihailenco** [comment]
No ideas here. This should probably be moved to uptrace-rust.
