### ISSUE TITLE
no metrics graphs with latest encoding dependency

### ISSUE THREAD

**Issue by tkoeppen** [uptrace/uptrace#391]
when I use latest commit (https://github.com/uptrace/uptrace/commit/8ed72ec878dddbc7331cc19d355ba908a94fd652)
that points to latest encoding commit from April (https://github.com/uptrace/uptrace/issues/390)

Everything else seems to be going well (metrics and traces data looking good),
except in metrics graphs, I see no or corrupt graphs.

Example below with uptrace own metrics:

61 HTTP requests counted, but the graph is empty.

<img width="1419" alt="Screenshot 2024-06-20 at 10 30 52" src="https://github.com/uptrace/uptrace/assets/1046814/de29b08b-8da5-4737-bad6-1d69cef439d6">

Also when metrics are 0, on the bottom of the graph view usually a blue line appears,
what is missing with the latest build.

When I return the original 1.7.6 version the graphs look okay.

built with make uptrace-linux_arm64 and started with cd <project_dir>/docker/example docker-compose up
pnpm -v  9.4.0
npm -v 10.8.1
Node.js v20.13.1
go version go1.22.4 darwin/arm64

Have not read through all the latest encoding changes and not sure where to start tracing the graph rendering.
Browser debug console and uptrace.log (debug) has no errors.

**Comment by vmihailenco** [comment]
Seems to be working here on the master branch

![http-server](https://github.com/uptrace/uptrace/assets/290976/dc7c3781-6fa8-4a13-9037-899479d71db2)

**Comment by tkoeppen** [comment]
thanks for the quick double-check. was a local build issue.
get correct graphs now
<img width="1411" alt="Screenshot 2024-06-20 at 13 16 37" src="https://github.com/uptrace/uptrace/assets/1046814/0d6dc15f-174e-44ee-8580-e27c4ad7175d">

**Comment by tkoeppen** [comment]
I was too quick with my last comment. I can reproduce the issue.
I tested in the last comment not latest master, but pointed to the old docker image in example docker-compose.yml.

When using latest master, I can reproduce it.
Debugged  a little bit further and can see, that old versions (1.7.6) returned on this URLs 0 instead of null.

URL:
nok http://localhost:14318/internal/v1/metrics/1/timeseries?time_gte=2024-06-20T10:34:00.000Z&time_lt=2024-06-20T11:34:00.000Z&time_offset=0&metric[]=http_server_duration&alias[]=srv_dur&query=per_min(count($srv_dur))+as+req_per_min+%7C+where+service_name+%3D+%22serve%22+%7C+where+host_name+%3D+%2246884e0b9918%22&min_interval=0

Left is 1.7.6 version, right is recent master branch version:

<img width="1339" alt="Screenshot 2024-06-20 at 14 18 01" src="https://github.com/uptrace/uptrace/assets/1046814/69f0b120-1c1d-4548-8cde-3c2035e51276">

This may cause the graph display issue.

**Comment by tkoeppen** [comment]
yes, it look like there time series data. 
To exclude anything else, the test was made with the original code from master, and example/docker-compose.yml
the data are the uptrace own produced metrics (after running some minutes, empty or existing clickhouse database, same problem with empty graph on both).

The first screenshot says, there are 5 time series.
The second screenshot says, there are 123 count(duration) per minute.

<img width="1386" alt="Screenshot 2024-06-21 at 09 07 29" src="https://github.com/uptrace/uptrace/assets/1046814/e4ca1d51-9d70-46e1-a4bf-6ed6f5b669cc">
<img width="1184" alt="Screenshot 2024-06-21 at 09 07 03" src="https://github.com/uptrace/uptrace/assets/1046814/44bbd5a5-4e38-4c48-90d7-c235efeec9f7">

It look like, that the data is there, but suddenly maybe the new encoding version translates to null instead of 0.
Have not checked how timeseries are stored in clickhouse, internally. So cannot tell, if the issue happen when storing the data in clickhouse with the master branch or when reading from clickhouse and converting it to the above endpoint /internal/v1/metrics/1/timeseries.

**Comment by tkoeppen** [comment]
When there is more data (wait longer), graphs appear.
At the beginning, the line from 0 to first data is missing, maybe that is the null vs. 0 topic only.
Test was made again with empty clickhouse database and original uptrace metrics only.

2 more examples (included 5 min. data):

<img width="1405" alt="Screenshot 2024-06-21 at 09 27 10" src="https://github.com/uptrace/uptrace/assets/1046814/7149f180-0aae-4552-b2d4-c34c5d36ba30">
<img width="1194" alt="Screenshot 2024-06-21 at 09 19 47" src="https://github.com/uptrace/uptrace/assets/1046814/84b2f47a-d7a3-4053-adf7-88cd2eff21e5">

**Comment by vmihailenco** [comment]
I am closing this issue since it is working for me and there are no similar reports....
