### ISSUE TITLE
Severity 'Information' not converted to INFO

### ISSUE THREAD

**Issue by arend-melissant-tnt** [uptrace/uptrace#399]
Hi,

looking at the code, it seems 'information' and 'INFORMATION' are converted to INFO, but .net sends logs with severity 'Information', which are shown as error...

maybe the conversion should be case insensitive?

Best regards
Arend Melissant

**Comment by vmihailenco** [comment]
Should be fixed by https://github.com/uptrace/uptrace/commit/e515258bdb09742cd45c1ab27751cca06c006dfd
