### ISSUE TITLE
DB::Exception: Column `time` is not under aggregate function and not in GROUP BY

### ISSUE THREAD

**Issue by Ax1an** [uptrace/uptrace#4]
![image](https://user-images.githubusercontent.com/28091237/150924378-7566e5ff-49c7-43a6-9ed5-bfbc5695132d.png)

ClickHouse version: 21.11.11.1

**Comment by vmihailenco** [comment]
@Ax1an this should be fixed by https://github.com/uptrace/uptrace/commit/aed295ad32577a0592a3ecbb61a04f5a305b8181. Can you make sure you are running v0.2.1?

**Comment by Ax1an** [comment]
@vmihailenco OK, I'll pull down the latest code and try again.

**Comment by Ax1an** [comment]
@vmihailenco After using the latest code, the problem is solved.
