### ISSUE TITLE
Offer to Translate Documentation into Chinese

### ISSUE THREAD

**Issue by naiqianz** [uptrace/uptrace#400]
Hello,

While researching observability, I recently discovered this project and found it very intriguing. I noticed the documentation at https://uptrace.dev/get/get-started.html and wondered if there is a need for a Chinese translation. I would be happy to assist with this if needed.

**Comment by goodsxx** [comment]
Great, I really need it. There are too many machine translation errors. (That's right, this sentence is also a machine translation)
