### ISSUE TITLE
Incorrect pagination

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/uptrace#407]
It says it has "16 spans", but on the first page I only see 10 spans, on  the second page only 1.

**Comment by vmihailenco** [comment]
I can't reproduce this when using the data that Uptrace generates after installation.

**Comment by ttaghavi** [comment]
It somehow "loses" up to 5 rows.

Here is my case:

12 results => results only in 1 page with 10 rows (no pagination option, rows 11-12 are impossible to vew)
17 results => results in 2 pages, first with 10 rows, second with 2 rows (rows 11-15 are impossible to view)
