### ISSUE TITLE
Running uptrace locally with docker compose and getting funny logs

### ISSUE THREAD

**Issue by CVxTz** [uptrace/uptrace#434]
hello ! 

I am running uptrace locally for testing and I am getting some logs like:

FATAL Pretty pretty pretty good
ERROR A bug was encountered but not in Vector, which doesn't have bugs
warning We're gonna need a bigger boat
ERROR Maybe we just shouldn't use computers
FATAL #hugops to everyone who has to deal with this
FATAL A bug was encountered but not in Vector, which doesn't have bugs

I appreciate the humor but I would like to get rid of them. How can I do that ? 

Thanks !

**Comment by avodaqstephan** [comment]
Came here to ask exactly the same question. I'd like to only feed my own data. :)

**Comment by CVxTz** [comment]
Thank you very much @avodaqstephan !
