### ISSUE TITLE
Add Distributed Table to Uptrace Schema

### ISSUE THREAD

**Issue by jkrech17** [uptrace/uptrace#59]
With the addition of ch_schema.replicated it would also be useful to have an option if you want to just use a Distributed Engine that would point to either the MergeTree tables or ReplicatedMergeTree tables.

In some cases, you may want to load balance across servers and not necessarily use replication.  

Thanks!

**Comment by vmihailenco** [comment]
Should be addressed by adding `ch_schema.cluster` option in https://github.com/uptrace/uptrace/commit/973c3a7021ecb5cdecf6df5369a77386022d45b1
