### ISSUE TITLE
Single Sign-On or a JWT token with explanation how to sign it

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/uptrace#76]

**Comment by derN3rd** [comment]
For us JWT token authentication with Cloudflare Access ([docs here](https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/validating-json/)) would be the best solution.

As uptrace is written in golang, it would be probably the easiest way to enable a config just for cloudflare access, as their jwts need certUrl handling, AUD to be configurable and a specific header value to look for the jwt token (or the CF_AUTHORIZATION cookie).

They even provide an example in go here: https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/validating-json/#golang-example

Also we must ensure that the [fields in the JWT token](https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/application-token/#payload) are used/mapped correctly to the values that uptrace expects or needs

**Comment by vmihailenco** [comment]
@derN3rd @aramperes do you happen to know if it is possible to use Cloudflare Access to protect http://localhost:19876/ so I can test this locally? Any hints would be appreciated...

**Comment by derN3rd** [comment]
> @derN3rd @aramperes do you happen to know if it is possible to use Cloudflare Access to protect http://localhost:19876/ so I can test this locally? Any hints would be appreciated...

Yes, you can run a [cloudflared tunnel](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/install-and-setup/tunnel-guide/local/run-tunnel/) which is basically a direct connection from your localhost to their datacenter. The url that it spits out can be used to setup a dns record on cloudflare which then [can be used in Cloudflare Access](https://developers.cloudflare.com/cloudflare-one/applications/configure-apps/self-hosted-apps/) to add some restrictions on who can access it

**Comment by vmihailenco** [comment]
@derN3rd I was afraid I need a tunnel... that seems to require a lot of configuration.

Could you shed some light on who & when is supposed to send/set `Cf-Access-Jwt-Assertion` header or `CF-Authorization` cookie in [golang](https://developers.cloudflare.com/cloudflare-one/identity/authorization-cookie/validating-json/#golang-example) example ?

Cloudflare should not be able to set a cookie on a different domain and I also don't see how it can pass me JWT via a header... Does it mean that the Uptrace app is supposed to be only available under `*.cloudflareaccess.com` domain?

**Comment by vmihailenco** [comment]
It is also not clear what is the purpose of the apps I can configure there if they can't get a cookie/header

![cf-apps](https://user-images.githubusercontent.com/290976/190597339-88273082-9a1c-4924-b28f-a95ecf2dcd54.png)

**Comment by derN3rd** [comment]
Short example config for cloudflared

/etc/cloudflared/config.yml
```yml
tunnel: <tunnel id (not sure if this was automatically filled)>
credentials-file: /root/.cloudflared/<credentials file>.json
logfile: /var/log/cloudflared/out.log
originRequest:
  connectTimeout: 120s

ingress:
  - hostname: behindcfaccess-uptrace.mydomain.com
    service: http://127.0.0.1:19876
  - service: http_status:404
```

The application you add in Cloudflare Access must be a Cloudflare proxied DNS entry. Otherwise they will just link to it, because they cannot proxy a private subnet IP. Only CF proxied URLs can be protected by them.

I really recommend going through this tutorial by them: 
https://developers.cloudflare.com/cloudflare-one/applications/configure-apps/self-hosted-apps/

**Comment by derN3rd** [comment]
The easiest way to test if all of this works is to add this to your tunnel config:

```
  - hostname: behindcfaccess-uptrace.mydomain.com
    service: https://httpbin.org
```

And access it, after you configured this domain in your Cloudflare settings and enabled Cloudflare Access for it.
Then you can see all the headers and metadata that will be send by Cloudflare.

**Comment by vmihailenco** [comment]
>The application you add in Cloudflare Access must be a Cloudflare proxied DNS entry. Otherwise they will just link to it, >because they cannot proxy a private subnet IP. Only CF proxied URLs can be protected by them.

This help, thanks.

>The application you add in Cloudflare Access must be a Cloudflare proxied DNS entry

Okay, looks like I also need a subdomain managed by Cloudflare to try this out. I guess we will need some volunteers to test Cloudflare Access integration, because I am not ready to go as far as buying a domain...

**Comment by vmihailenco** [comment]
The cloudflare integration can be enabled in the [config](https://github.com/uptrace/uptrace/pull/87) by uncommenting the lines:

```yaml
# user_providers:
#   # Cloudflare user provider: uses Cloudflare Zero Trust Access (Identity)
#   # See https://developers.cloudflare.com/cloudflare-one/identity/ for more info.
#   cloudflare:
#     # The base URL of the Cloudflare Zero Trust team.
#     team_url: https://myteam.cloudflareaccess.com
#     # The Application Audience (AUD) Tag for this application.
#     # You can retrieve this from the Cloudflare Zero Trust 'Access' Dashboard.
#     audience: bea6df23b944e4a0cd178609ba1bb64dc98dfe1f66ae7b918e563f6cf28b37e0
```

Would be nice if someone can test the integration before I blindly write some docs :)

**Comment by aramperes** [comment]
I'll be able to test it tonight

**Comment by aramperes** [comment]
Cloudflare Access works by protecting a subdomain like `uptrace.mydomain.com` under it. If the user is not logged in to Cloudflare Access, Cloudflare will redirect the browser to `mydomain.cloudflareaccess.com` so the user can verify their identity as required (PIN, GitHub login, etc.). Once Cloudflare authorizes the user for the application, they are redirected back to `uptrace.mydomain.com`.

Since Cloudflare is a full MITM, it injects the `Cf-Access-Jwt-Assertion` on every request, as long as the user is logged in. It also sets a cookie.

For example, I protected https://trace.poire.dev/ under Cloudflare Access with the `Uptrace` app. It redirects you to `https://wavy.cloudflareaccess.com/...`, which then requires a GitHub login (and you have to be in the @wavy org to go through).

Currently the domain points to nowhere, I'll be deploying Uptrace on my server tonight to test the token validation.

**Comment by aramperes** [comment]
Tested, with a [Helm chart](https://github.com/aramperes/momoperes.ca/tree/master/uptrace) I threw together to deploy in my k8s cluster:


https://user-images.githubusercontent.com/6775216/190835678-e00f225f-768c-4c47-8cf0-4dedbe001866.mov

**Comment by vmihailenco** [comment]
I've added some docs about Keycloak and Google Cloud:
- https://uptrace.dev/get/auth-keycloak.html
- https://uptrace.dev/get/auth-google.html

Cloudflare still requires some work.

**Comment by vmihailenco** [comment]
Also added some details about Cloudflare - https://uptrace.dev/get/auth-cloudflare.html. Thanks @aramperes for contributing this.
