### ISSUE TITLE
Issue in traefik routing to OTLP/HTTP port

### ISSUE THREAD

**Issue by rinshadka** [uptrace/uptrace#8]
I am running uptrace in docker and used traefik for routing the OLTP/HTTP requests and its working while accessing the UI, since UI and OTLP/HTTP are the same ports , OTLP/HTTP also should work.
But while sending trace data to OLTP/HTTP via traefik, we are not getting the POST request in uptrace.

But if we use the direct port we can see the POST requests in the docker logs like below.

```

[bunrouter]  07:04:03.145   200        188µs   POST     /v1/traces
[bunrouter]  07:04:03.149   200        177µs   POST     /v1/traces
```
Thanks.

**Comment by vmihailenco** [comment]
Uptrace does not do anything special with OTLP/HTTP. it is just a Go HTTP server. Are you able to use that setup with OpenTelemetry Collector?

Also, do you really need to use Docker+traefik? You can find a pre-compiled binary in [releases](https://github.com/uptrace/uptrace/releases) - it is much easier to administer...

Not sure how else I can help. This sounds like a problem with traefik and/or Docker and I don't have much experience with neither of them...
