### ISSUE TITLE
Add support for Sentry ingestion API / accepting spans from Sentry SDK

### ISSUE THREAD

**Issue by vmihailenco** [uptrace/uptrace#83]
Uptrace should accept data from Sentry SDK/clients in Sentry format and store it in the Uptrace database. The main benefit is the ability to use https://github.com/getsentry/sentry-javascript which is years ahead of opentelemetry-js.

A good start would be to configure sentry-go to send data to Uptrace:

```go
package main

import (
	"log"
	"time"

	"github.com/getsentry/sentry-go"
)

func main() {
	err := sentry.Init(sentry.ClientOptions{
		Dsn: "http://examplePublicKey@localhost:14318/0",
		// Enable printing of SDK debug messages.
		// Useful when getting started or trying to figure something out.
		Debug: true,
	})
	if err != nil {
		log.Fatalf("sentry.Init: %s", err)
	}
	// Flush buffered events before the program terminates.
	// Set the timeout to the maximum duration the program can afford to wait.
	defer sentry.Flush(2 * time.Second)
}
```

Then check what data Sentry SDK sends to the backend and try to map it to internal Uptrace datastructures:
- https://github.com/uptrace/uptrace/blob/master/pkg/tracing/span.go#L31-L60 - span representation. Can be used to store errors as well.
- https://github.com/uptrace/uptrace/blob/master/pkg/tracing/otlp_trace.go#L167-L173 here is how we accept, convert, and process spans.

The Sentry API looks rather simple and clean:
- https://pkg.go.dev/github.com/getsentry/sentry-go#Event
- https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/sentryexporter/sentry_exporter.go#L437-L461

**Comment by big-thousand** [comment]
I think it https://github.com/getsentry/sentry-go/issues/486 will support it

**Comment by vmihailenco** [comment]
Interesting, but it looks like it is about converting Otel spans to Sentry transactions while this issue is about supporting Sentry ingestion API in Uptrace.

This is needed mainly to use [@sentry/browser](https://github.com/getsentry/sentry-javascript/tree/master/packages/browser) which is years ahead of OpenTelemetry. In all other cases including Node.js OpenTelemetry is more than adequate.

**Comment by vmihailenco** [comment]
[Ingesting data into Uptrace backend using Sentry clients](https://uptrace.dev/get/ingest/sentry.html)
