### ISSUE TITLE
How to setup tail-based sampling

### ISSUE THREAD

**Issue by hjweddie** [uptrace/uptrace#85]
Our golang programs export data to uptrace 14317/14318 ports with UPTRACE_DSN header, but do not know how to do tail-based sampling

**Comment by vmihailenco** [comment]
Uptrace itself does not support tail-based sampling and instead you should configure it in OpenTelemetry Collector. Try to follow https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor and later we will provide a more detailed tutorial.

**Comment by hjweddie** [comment]
I undestand that how to use otel collector for tail-based sampling, but feel confused about how to let otel collector distribute span/trace to different project in Uptrace

**Comment by hjweddie** [comment]
Is it necessary to deploy different otel collectors exporting to Uptrace for different projects?
Is it possible to deploy one collectors for different projects?

**Comment by vmihailenco** [comment]
You can use [routing](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/routingprocessor) to route spans to different exporters. You will need s separate exporter for each project.

Having a separate Otel Collector per project is also an option.

**Comment by hjweddie** [comment]
thanks, I have used routing processor it to archive tail-base sampling
