### ISSUE TITLE
Support an external database (postgres, mysql)

### ISSUE THREAD

**Issue by aramperes** [uptrace/uptrace#90]
Supporting an external SQL database as an alternative to sqlite would be useful for running Uptrace in a stateless environment like Kubernetes. This could allow Uptrace to run with multiple replicas, and enable rolling restarts to reduce downtime.

Keeping sqlite as the default reduces dependencies for a quick setup, and still works well in `systemd` and `docker-compose` setups.

Personally I have no preference between Postgres and MySQL. If Bun is agnostic to all 3 options, that's even better.

**Comment by vmihailenco** [comment]
I can take this and document how to use PostgreSQL with Uptrace. It still won't be a default choice because sqlite works okay in most cases. My biggest concern is the lack of testing with other DBMS, but I guess this is where community can help.

**Comment by vmihailenco** [comment]
>Personally I have no preference between Postgres and MySQL. If Bun is agnostic to all 3 options, that's even better.

Postgres and SQLite have more features in common so it is easier to support those 2. MySQL will probably require a bit more work.

**Comment by jeffbicca** [comment]
I personally still think that it would be great to have both SQLite and Postgres supported as each option have it's own advantages and disadvantages. I say having flexibility is the key here.

For example in the company where I work we are unable to setup a new Postgres instance in our "on-prem private cloud". I would need to envolve another team and/or infrastructure to maybe run an instance dedicated to Uptrace.

As @aramperes mentioned earlier I understand perfectly that Postgres is better for a higher availability cenario. But in the other hand there are a couple of other situations that less infrastructure is the simplest and the better approach.
