### ISSUE TITLE
Duration in Explore view seems to be 1000 too small

### ISSUE THREAD

**Issue by Etienne-Carriere** [uptrace/uptrace#93]
Hello,

I am using 
* uptrace 1.0.3 
* Data comes from 
  * Opentelemetry collector
  * Jaeger + Opentracing source data 

I have some issues with the duration unit in some dashboard : 

On the dashboard /explore/<project_id>/groups, I see : 
![image](https://user-images.githubusercontent.com/2909360/191513441-0ef665f9-d886-434d-bb26-b24b40ed74f7.png)

We see that for group "Celery:run:check_clients_nonprd_resources" we have a max span duration of 302 ms : 
* In the API call , we can see the max value is 301977114000 which is ~301e9 
* When I deep dive, I see that the longest span are 5 minutes which is in fact 301 seconds (I verified with Jaeger) 
![image](https://user-images.githubusercontent.com/2909360/191514166-aebdd758-c039-40db-b75b-f2862182033a.png)
* When I look in Clickhouse database (via the query log), I replayed the Clickhouse query : 
```
SELECT
    group_id AS `span.group_id`,
    sum(count) / 60 AS `span.count_per_min`,
    sumIf(count, status_code = 'error') / sum(count) AS `span.error_pct`,
    quantileTDigest(0.5)(toFloat64OrDefault(duration)) AS `p50(span.duration)`,
    quantileTDigest(0.9)(toFloat64OrDefault(duration)) AS `p90(span.duration)`,
    quantileTDigest(0.99)(toFloat64OrDefault(duration)) AS `p99(span.duration)`,
    max(duration) AS `max(span.duration)`,
    any(system) AS `span.system`,
    any(name) AS `span.name`,
    any(event_name) AS `span.event_name`
FROM spans_index AS s
WHERE (project_id = 2) AND (time >= toDateTime('2022-09-21 12:02:00', 'UTC')) AND (time < toDateTime('2022-09-21 13:02:00', 'UTC')) AND (system = 'service:ccp-paris_prd') AND (kind = 'server')
GROUP BY `span.group_id`
ORDER BY `p99(span.duration)` DESC
LIMIT 1000

Query id: 32d3e1dd-3116-428a-ba9b-142c58e1324e

┌────────span.group_id─┬───span.count_per_min─┬─────span.error_pct─┬─p50(span.duration)─┬─p90(span.duration)─┬─p99(span.duration)─┬─max(span.duration)─┬─span.system───────────┬─span.name─────────────────────────────────────────────────────┬─span.event_name─┐
│ 14900324603554143372 │                 0.85 │                  0 │       284028930000 │       296918750000 │       301977100000 │       301977114000 │ service:ccp-paris_prd │ Celery:run:check_clients_nonprd_resources                     │                 │
```

I suppose an issue at the front visualization . As I am not a vue expert, I was not able to dig in

**Comment by vmihailenco** [comment]
Thanks for the report and @aramperes for the quick fix.

**Comment by Etienne-Carriere** [comment]
Thank you for the fast fix. What is the expected next release date ?

**Comment by vmihailenco** [comment]
Probably early next week.
